// Hand-authored word/paragraph translation glossary for the Modul 2 reading
// passages (lib/content-gen/modul2-reading.ts). Keyed by the passages'
// stable `passageId`, not by DB Item id. Scope is deliberately limited to
// these 12 existing passages — see components/TranslatablePassage.tsx for
// how a passage outside this set falls back to plain, non-interactive text.

import type { PassageGlossary } from "@/types";

export const MODUL2_GLOSSARIES: PassageGlossary[] = [
  {
    passageId: "m2-t1-arbejde-peter-hospital",
    englishSummary:
      "Peter works at a hospital in Odense as a nurse. He starts at 7am, helps patients and talks with doctors during the day, and takes a lunch break at noon. He's happy in his job — it's hard, but also exciting.",
    words: [
      { surface: "arbejder", lemma: "arbejde", englishGloss: "works", partOfSpeech: "verb", inflectionNote: "present tense of 'at arbejde' (to work) — Danish present tense adds -er and is the same for all persons (jeg/du/han arbejder)." },
      { surface: "hospital", lemma: "hospital", englishGloss: "hospital", partOfSpeech: "noun", inflectionNote: "neuter (et-word): et hospital / hospitalet." },
      { surface: "er", lemma: "være", englishGloss: "is", partOfSpeech: "verb", inflectionNote: "present tense of 'at være' (to be) — irregular, one form for all persons." },
      { surface: "sygeplejerske", lemma: "sygeplejerske", englishGloss: "nurse", partOfSpeech: "noun", inflectionNote: "common gender (en-word): en sygeplejerske / sygeplejersken." },
      { surface: "starter", lemma: "starte", englishGloss: "starts", partOfSpeech: "verb", inflectionNote: "present tense of 'at starte', regular -er verb." },
      { surface: "arbejde", lemma: "arbejde", englishGloss: "work", partOfSpeech: "noun", inflectionNote: "same spelling as the verb stem, but here a neuter noun: 'på arbejde' (at work), 'sit arbejde' (his work)." },
      { surface: "klokken", lemma: "klokke", englishGloss: "o'clock / the clock", partOfSpeech: "noun", inflectionNote: "definite form of 'klokke' — used before a number to tell time: klokken syv = seven o'clock." },
      { surface: "morgenen", lemma: "morgen", englishGloss: "the morning", partOfSpeech: "noun", inflectionNote: "definite singular of 'morgen' (-en suffix instead of a separate article)." },
      { surface: "hjælper", lemma: "hjælpe", englishGloss: "helps", partOfSpeech: "verb", inflectionNote: "present tense of 'at hjælpe'." },
      { surface: "patienterne", lemma: "patient", englishGloss: "the patients", partOfSpeech: "noun", inflectionNote: "definite plural: patient → patienter (plural) → patienterne (definite plural, -ne suffix)." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "taler", lemma: "tale", englishGloss: "talks", partOfSpeech: "verb", inflectionNote: "present tense of 'at tale' (to talk/speak)." },
      { surface: "lægerne", lemma: "læge", englishGloss: "the doctors", partOfSpeech: "noun", inflectionNote: "definite plural: læge → læger (plural) → lægerne (definite plural)." },
      { surface: "tolv", lemma: "tolv", englishGloss: "twelve", partOfSpeech: "numeral", inflectionNote: "does not inflect." },
      { surface: "holder", lemma: "holde", englishGloss: "takes / holds", partOfSpeech: "verb", inflectionNote: "present tense of 'at holde'; 'holder pause' is a fixed expression meaning 'takes a break'." },
      { surface: "pause", lemma: "pause", englishGloss: "break", partOfSpeech: "noun", inflectionNote: "common gender: en pause / pausen." },
      { surface: "spiser", lemma: "spise", englishGloss: "eats", partOfSpeech: "verb", inflectionNote: "present tense of 'at spise'." },
      { surface: "frokost", lemma: "frokost", englishGloss: "lunch", partOfSpeech: "noun", inflectionNote: "common gender, usually used without an article: spiser frokost." },
      { surface: "kantinen", lemma: "kantine", englishGloss: "the canteen", partOfSpeech: "noun", inflectionNote: "definite singular: kantine → kantinen." },
      { surface: "glad", lemma: "glad", englishGloss: "happy", partOfSpeech: "adjective", inflectionNote: "base form, agrees with 'Peter' (common gender singular): 'Peter er glad'." },
      { surface: "hårdt", lemma: "hård", englishGloss: "hard", partOfSpeech: "adjective", inflectionNote: "neuter form of 'hård' (+t) because it describes 'det' (it) — Danish adjectives take -t to agree with neuter subjects." },
      { surface: "men", lemma: "men", englishGloss: "but", partOfSpeech: "conjunction", inflectionNote: "joins two contrasting clauses." },
      { surface: "også", lemma: "også", englishGloss: "also / too", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "spændende", lemma: "spændende", englishGloss: "exciting", partOfSpeech: "adjective", inflectionNote: "present-participle adjective (from 'at spænde') — same form for all genders/numbers." },
      { surface: "han", lemma: "han", englishGloss: "he", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person singular masculine." },
      { surface: "syv", lemma: "syv", englishGloss: "seven", partOfSpeech: "numeral", inflectionNote: "does not inflect." },
      { surface: "dagen", lemma: "dag", englishGloss: "the day", partOfSpeech: "noun", inflectionNote: "definite singular: dag → dagen; 'om dagen' = 'during the day'." },
      { surface: "sit", lemma: "sin", englishGloss: "his (own)", partOfSpeech: "pronoun", inflectionNote: "reflexive possessive, neuter form (+t) to agree with neuter 'arbejde' — refers back to the subject ('Peter... sit arbejde' = his own work)." },
      { surface: "det", lemma: "det", englishGloss: "it", partOfSpeech: "pronoun", inflectionNote: "neuter subject pronoun, used for the impersonal 'it' in 'det er hårdt' (it's hard)." },
    ],
  },
  {
    passageId: "m2-t1-uddannelse-maria-sprogskole",
    englishSummary:
      "Maria goes to language school three times a week. She reads Danish in the morning and does homework in the evening. Her classmates come from many countries, and the teacher speaks slowly. School is fun but also difficult.",
    words: [
      { surface: "går", lemma: "gå", englishGloss: "goes / walks", partOfSpeech: "verb", inflectionNote: "present tense of 'at gå'; 'går på sprogskole' means 'attends language school'." },
      { surface: "sprogskole", lemma: "sprogskole", englishGloss: "language school", partOfSpeech: "noun", inflectionNote: "compound noun: sprog (language) + skole (school), common gender." },
      { surface: "gange", lemma: "gang", englishGloss: "times", partOfSpeech: "noun", inflectionNote: "plural of 'gang' (an occurrence/time); 'tre gange' = three times." },
      { surface: "ugen", lemma: "uge", englishGloss: "the week", partOfSpeech: "noun", inflectionNote: "definite singular: uge → ugen; 'om ugen' = per week." },
      { surface: "læser", lemma: "læse", englishGloss: "reads", partOfSpeech: "verb", inflectionNote: "present tense of 'at læse'." },
      { surface: "dansk", lemma: "dansk", englishGloss: "Danish", partOfSpeech: "noun/adjective", inflectionNote: "the language name, uncapitalized in Danish unlike English." },
      { surface: "laver", lemma: "lave", englishGloss: "makes / does", partOfSpeech: "verb", inflectionNote: "present tense of 'at lave'; 'laver lektier' = 'does homework'." },
      { surface: "lektier", lemma: "lektie", englishGloss: "homework", partOfSpeech: "noun", inflectionNote: "plural of 'lektie', usually used in plural like English 'homework assignments'." },
      { surface: "aftenen", lemma: "aften", englishGloss: "the evening", partOfSpeech: "noun", inflectionNote: "definite singular: aften → aftenen." },
      { surface: "klassen", lemma: "klasse", englishGloss: "the class", partOfSpeech: "noun", inflectionNote: "definite singular: klasse → klassen." },
      { surface: "elever", lemma: "elev", englishGloss: "students", partOfSpeech: "noun", inflectionNote: "plural of 'elev' (+er)." },
      { surface: "lande", lemma: "land", englishGloss: "countries", partOfSpeech: "noun", inflectionNote: "irregular plural of 'land' (land → lande)." },
      { surface: "læreren", lemma: "lærer", englishGloss: "the teacher", partOfSpeech: "noun", inflectionNote: "definite singular: lærer → læreren." },
      { surface: "taler", lemma: "tale", englishGloss: "speaks", partOfSpeech: "verb", inflectionNote: "present tense of 'at tale'." },
      { surface: "langsomt", lemma: "langsom", englishGloss: "slowly", partOfSpeech: "adverb", inflectionNote: "adjective 'langsom' + -t used adverbially." },
      { surface: "eleverne", lemma: "elev", englishGloss: "the students", partOfSpeech: "noun", inflectionNote: "definite plural: elev → elever (plural) → eleverne (definite plural)." },
      { surface: "øver", lemma: "øve", englishGloss: "practice", partOfSpeech: "verb", inflectionNote: "present tense of 'at øve sig' (to practice, reflexive)." },
      { surface: "sammen", lemma: "sammen", englishGloss: "together", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "sjov", lemma: "sjov", englishGloss: "fun", partOfSpeech: "adjective", inflectionNote: "base form, agrees with 'sprogskolen' (common gender)." },
      { surface: "men", lemma: "men", englishGloss: "but", partOfSpeech: "conjunction", inflectionNote: "joins two contrasting clauses." },
      { surface: "svær", lemma: "svær", englishGloss: "difficult", partOfSpeech: "adjective", inflectionNote: "base form, common gender agreement (same pattern as 'sjov')." },
      { surface: "tre", lemma: "tre", englishGloss: "three", partOfSpeech: "numeral", inflectionNote: "does not inflect." },
      { surface: "hun", lemma: "hun", englishGloss: "she", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person singular feminine." },
      { surface: "morgenen", lemma: "morgen", englishGloss: "the morning", partOfSpeech: "noun", inflectionNote: "definite singular: morgen → morgenen; 'om morgenen' = 'in the morning'." },
      { surface: "er", lemma: "være", englishGloss: "are", partOfSpeech: "verb", inflectionNote: "present tense of 'at være' (to be)." },
      { surface: "fra", lemma: "fra", englishGloss: "from", partOfSpeech: "preposition", inflectionNote: "does not inflect." },
      { surface: "mange", lemma: "mange", englishGloss: "many", partOfSpeech: "pronoun", inflectionNote: "plural quantifier before plural nouns." },
      { surface: "sig", lemma: "sig", englishGloss: "themselves", partOfSpeech: "pronoun", inflectionNote: "third-person reflexive pronoun, used in 'øver sig' (practice)." },
      { surface: "sprogskolen", lemma: "sprogskole", englishGloss: "the language school", partOfSpeech: "noun", inflectionNote: "definite singular: sprogskole → sprogskolen." },
      { surface: "også", lemma: "også", englishGloss: "also / too", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
    ],
  },
  {
    passageId: "m2-t1-hverdagsliv-familien-nielsen",
    englishSummary:
      "The Nielsen family lives in an apartment in Copenhagen. They get up early and eat breakfast together. The kids bike to school and the parents take the bus to work. In the evening they cook and watch TV together, and spend weekends in the park or at home.",
    words: [
      { surface: "familien", lemma: "familie", englishGloss: "the family", partOfSpeech: "noun", inflectionNote: "definite singular: familie → familien." },
      { surface: "bor", lemma: "bo", englishGloss: "lives", partOfSpeech: "verb", inflectionNote: "present tense of 'at bo' (to live/reside)." },
      { surface: "lejlighed", lemma: "lejlighed", englishGloss: "apartment", partOfSpeech: "noun", inflectionNote: "common gender: en lejlighed / lejligheden." },
      { surface: "morgenen", lemma: "morgen", englishGloss: "the morning", partOfSpeech: "noun", inflectionNote: "definite singular: morgen → morgenen; 'om morgenen' = 'in the morning'." },
      { surface: "står", lemma: "stå", englishGloss: "get up / stand", partOfSpeech: "verb", inflectionNote: "present tense of 'at stå op' (to get up)." },
      { surface: "tidligt", lemma: "tidlig", englishGloss: "early", partOfSpeech: "adverb", inflectionNote: "adjective 'tidlig' + -t used adverbially." },
      { surface: "spiser", lemma: "spise", englishGloss: "eat", partOfSpeech: "verb", inflectionNote: "present tense of 'at spise'." },
      { surface: "morgenmad", lemma: "morgenmad", englishGloss: "breakfast", partOfSpeech: "noun", inflectionNote: "compound: morgen (morning) + mad (food)." },
      { surface: "sammen", lemma: "sammen", englishGloss: "together", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "børnene", lemma: "barn", englishGloss: "the children", partOfSpeech: "noun", inflectionNote: "irregular plural+definite: barn → børn (plural) → børnene (definite plural)." },
      { surface: "cykler", lemma: "cykle", englishGloss: "bike / cycle", partOfSpeech: "verb", inflectionNote: "present tense of 'at cykle'." },
      { surface: "skole", lemma: "skole", englishGloss: "school", partOfSpeech: "noun", inflectionNote: "'i skole' (to/at school) drops the article, a fixed expression like 'i seng'." },
      { surface: "forældrene", lemma: "forældre", englishGloss: "the parents", partOfSpeech: "noun", inflectionNote: "'forældre' is inherently plural; definite form adds -ne." },
      { surface: "tager", lemma: "tage", englishGloss: "take", partOfSpeech: "verb", inflectionNote: "present tense of 'at tage'." },
      { surface: "bussen", lemma: "bus", englishGloss: "the bus", partOfSpeech: "noun", inflectionNote: "definite singular: bus → bussen (consonant doubled before -en)." },
      { surface: "aftenen", lemma: "aften", englishGloss: "the evening", partOfSpeech: "noun", inflectionNote: "definite singular: aften → aftenen." },
      { surface: "laver", lemma: "lave", englishGloss: "make / cook", partOfSpeech: "verb", inflectionNote: "present tense of 'at lave'; 'laver mad' = 'cooks'." },
      { surface: "mad", lemma: "mad", englishGloss: "food", partOfSpeech: "noun", inflectionNote: "uncountable, no plural." },
      { surface: "ser", lemma: "se", englishGloss: "watch / see", partOfSpeech: "verb", inflectionNote: "present tense of 'at se'; 'ser fjernsyn' = 'watches TV'." },
      { surface: "fjernsyn", lemma: "fjernsyn", englishGloss: "television", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "weekenden", lemma: "weekend", englishGloss: "the weekend", partOfSpeech: "noun", inflectionNote: "definite singular: weekend → weekenden." },
      { surface: "bruger", lemma: "bruge", englishGloss: "spend / use", partOfSpeech: "verb", inflectionNote: "present tense of 'at bruge'; 'bruger weekenden i parken' = 'spends the weekend in the park'." },
      { surface: "parken", lemma: "park", englishGloss: "the park", partOfSpeech: "noun", inflectionNote: "definite singular: park → parken." },
      { surface: "eller", lemma: "eller", englishGloss: "or", partOfSpeech: "conjunction", inflectionNote: "presents an alternative between two options." },
      { surface: "hjemme", lemma: "hjemme", englishGloss: "at home", partOfSpeech: "adverb", inflectionNote: "does not inflect (distinct from 'hjem', the noun 'home')." },
      { surface: "familien", lemma: "familie", englishGloss: "the family", partOfSpeech: "noun", inflectionNote: "definite singular: familie → familien." },
      { surface: "københavn", lemma: "København", englishGloss: "Copenhagen", partOfSpeech: "proper noun", inflectionNote: "city name, does not inflect." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "arbejde", lemma: "arbejde", englishGloss: "work", partOfSpeech: "noun", inflectionNote: "neuter noun; 'på arbejde' = 'at work'." },
    ],
  },
  {
    passageId: "m2-t1-medborgerskab-folketinget",
    englishSummary:
      "In Denmark, there are Folketing (parliament) elections every four years. All citizens over eighteen have the right to vote. Many Danes follow the news and discuss politics with family and friends — voting rights are an important part of democracy.",
    words: [
      { surface: "danmark", lemma: "Danmark", englishGloss: "Denmark", partOfSpeech: "proper noun", inflectionNote: "country name, does not inflect." },
      { surface: "valg", lemma: "valg", englishGloss: "election", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "folketinget", lemma: "Folketing", englishGloss: "the Folketing (Danish parliament)", partOfSpeech: "proper noun", inflectionNote: "definite form of 'Folketing', the name of Denmark's parliament." },
      { surface: "hvert", lemma: "hver", englishGloss: "every / each", partOfSpeech: "pronoun", inflectionNote: "neuter form of 'hver' (+t) to agree with neuter 'år' (year)." },
      { surface: "fjerde", lemma: "fjerde", englishGloss: "fourth", partOfSpeech: "numeral", inflectionNote: "ordinal number, invariable form." },
      { surface: "år", lemma: "år", englishGloss: "year", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "alle", lemma: "alle", englishGloss: "all", partOfSpeech: "pronoun", inflectionNote: "plural form used before plural nouns like 'borgere'." },
      { surface: "borgere", lemma: "borger", englishGloss: "citizens", partOfSpeech: "noun", inflectionNote: "plural of 'borger' (+e)." },
      { surface: "atten", lemma: "atten", englishGloss: "eighteen", partOfSpeech: "numeral", inflectionNote: "does not inflect." },
      { surface: "stemmeret", lemma: "stemmeret", englishGloss: "the right to vote", partOfSpeech: "noun", inflectionNote: "compound: stemme (vote) + ret (right)." },
      { surface: "mange", lemma: "mange", englishGloss: "many", partOfSpeech: "pronoun", inflectionNote: "plural quantifier, used before plural nouns." },
      { surface: "danskere", lemma: "dansker", englishGloss: "Danes", partOfSpeech: "noun", inflectionNote: "plural of 'dansker' (a Dane, +e)." },
      { surface: "følger", lemma: "følge", englishGloss: "follow", partOfSpeech: "verb", inflectionNote: "present tense of 'at følge'; 'følger med i nyhederne' = 'keep up with the news'." },
      { surface: "nyhederne", lemma: "nyhed", englishGloss: "the news", partOfSpeech: "noun", inflectionNote: "definite plural: nyhed → nyheder (plural) → nyhederne (definite plural)." },
      { surface: "taler", lemma: "tale", englishGloss: "talk", partOfSpeech: "verb", inflectionNote: "present tense of 'at tale'." },
      { surface: "politik", lemma: "politik", englishGloss: "politics", partOfSpeech: "noun", inflectionNote: "uncountable, no plural." },
      { surface: "familie", lemma: "familie", englishGloss: "family", partOfSpeech: "noun", inflectionNote: "common gender, indefinite form here (no article after 'med')." },
      { surface: "venner", lemma: "ven", englishGloss: "friends", partOfSpeech: "noun", inflectionNote: "plural of 'ven' (+ner)." },
      { surface: "vigtig", lemma: "vigtig", englishGloss: "important", partOfSpeech: "adjective", inflectionNote: "common-gender form, agrees with 'ret' (en-word)." },
      { surface: "ret", lemma: "ret", englishGloss: "right", partOfSpeech: "noun", inflectionNote: "common gender: en ret (a right)." },
      { surface: "demokrati", lemma: "demokrati", englishGloss: "democracy", partOfSpeech: "noun", inflectionNote: "neuter: et demokrati." },
      { surface: "er", lemma: "være", englishGloss: "is / are", partOfSpeech: "verb", inflectionNote: "present tense of 'at være' (to be)." },
      { surface: "har", lemma: "have", englishGloss: "have", partOfSpeech: "verb", inflectionNote: "present tense of 'at have'." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
    ],
  },
  {
    passageId: "m2-t2-arbejde-peter-jobskift",
    englishSummary:
      "Last year Peter changed jobs because he wanted to work closer to home. He applied for a position at a hospital in his own town and got the job after an interview. The new job has the same tasks but a much shorter commute — Peter is happy about the change because he now has more time for his family.",
    words: [
      { surface: "sidste", lemma: "sidste", englishGloss: "last", partOfSpeech: "adjective", inflectionNote: "invariable form of 'sidst' used before a noun: 'sidste år' = 'last year'." },
      { surface: "skiftede", lemma: "skifte", englishGloss: "changed", partOfSpeech: "verb", inflectionNote: "past tense of 'at skifte' — regular verb, past tense adds -ede." },
      { surface: "job", lemma: "job", englishGloss: "job", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason; the verb stays in normal position (skifte job, fordi han ville...)." },
      { surface: "ville", lemma: "ville", englishGloss: "wanted to", partOfSpeech: "verb", inflectionNote: "past tense of the modal verb 'vil' (want to)." },
      { surface: "tættere", lemma: "tæt", englishGloss: "closer", partOfSpeech: "adjective", inflectionNote: "comparative form of 'tæt' (close) — add -ere for comparatives." },
      { surface: "hjem", lemma: "hjem", englishGloss: "home", partOfSpeech: "noun", inflectionNote: "neuter noun here (his home), not the adverb 'hjemme'." },
      { surface: "søgte", lemma: "søge", englishGloss: "applied for", partOfSpeech: "verb", inflectionNote: "past tense of 'at søge' (to seek/apply); -te ending marks past tense for this verb class." },
      { surface: "stilling", lemma: "stilling", englishGloss: "position", partOfSpeech: "noun", inflectionNote: "common gender: en stilling." },
      { surface: "egen", lemma: "egen", englishGloss: "own", partOfSpeech: "adjective", inflectionNote: "common-gender form of 'egen' (own), agrees with 'by' (en-word)." },
      { surface: "fik", lemma: "få", englishGloss: "got", partOfSpeech: "verb", inflectionNote: "past tense of 'at få' (to get) — irregular." },
      { surface: "jobbet", lemma: "job", englishGloss: "the job", partOfSpeech: "noun", inflectionNote: "definite singular: job → jobbet (consonant doubled before -et)." },
      { surface: "samtale", lemma: "samtale", englishGloss: "interview / conversation", partOfSpeech: "noun", inflectionNote: "common gender: en samtale." },
      { surface: "arbejdede", lemma: "arbejde", englishGloss: "worked", partOfSpeech: "verb", inflectionNote: "past tense of 'at arbejde' — regular -ede ending." },
      { surface: "opgaver", lemma: "opgave", englishGloss: "tasks", partOfSpeech: "noun", inflectionNote: "plural of 'opgave' (+r)." },
      { surface: "før", lemma: "før", englishGloss: "before", partOfSpeech: "adverb/conjunction", inflectionNote: "here an adverb meaning 'previously'; can also introduce a subordinate clause." },
      { surface: "men", lemma: "men", englishGloss: "but", partOfSpeech: "conjunction", inflectionNote: "joins two contrasting clauses." },
      { surface: "transporttiden", lemma: "transporttid", englishGloss: "the commute time", partOfSpeech: "noun", inflectionNote: "compound noun (transport + tid) in definite form: transporttid → transporttiden." },
      { surface: "blev", lemma: "blive", englishGloss: "became", partOfSpeech: "verb", inflectionNote: "past tense of 'at blive' (to become) — irregular." },
      { surface: "kortere", lemma: "kort", englishGloss: "shorter", partOfSpeech: "adjective", inflectionNote: "comparative of 'kort' (short) — add -ere." },
      { surface: "var", lemma: "være", englishGloss: "was", partOfSpeech: "verb", inflectionNote: "past tense of 'at være' (to be) — irregular." },
      { surface: "skiftet", lemma: "skifte", englishGloss: "the change", partOfSpeech: "noun", inflectionNote: "same word as the verb 'skifte', used here as a definite neuter noun (the change)." },
      { surface: "nu", lemma: "nu", englishGloss: "now", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "havde", lemma: "have", englishGloss: "had", partOfSpeech: "verb", inflectionNote: "past tense of 'at have' (to have)." },
      { surface: "mere", lemma: "meget", englishGloss: "more", partOfSpeech: "adverb", inflectionNote: "comparative of 'meget' (much) — irregular comparative." },
      { surface: "tid", lemma: "tid", englishGloss: "time", partOfSpeech: "noun", inflectionNote: "common gender: en tid." },
      { surface: "familien", lemma: "familie", englishGloss: "the family", partOfSpeech: "noun", inflectionNote: "definite singular: familie → familien." },
      { surface: "han", lemma: "han", englishGloss: "he", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person singular masculine." },
      { surface: "sit", lemma: "sin", englishGloss: "his (own)", partOfSpeech: "pronoun", inflectionNote: "reflexive possessive, neuter form (+t), refers back to the subject Peter." },
      { surface: "hospital", lemma: "hospital", englishGloss: "hospital", partOfSpeech: "noun", inflectionNote: "neuter: et hospital." },
      { surface: "sin", lemma: "sin", englishGloss: "his (own)", partOfSpeech: "pronoun", inflectionNote: "reflexive possessive, common-gender form, agrees with 'by' (en-word)." },
      { surface: "by", lemma: "by", englishGloss: "town", partOfSpeech: "noun", inflectionNote: "common gender: en by." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "efter", lemma: "efter", englishGloss: "after", partOfSpeech: "preposition", inflectionNote: "does not inflect." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "samme", lemma: "samme", englishGloss: "same", partOfSpeech: "adjective", inflectionNote: "invariable form used with 'de' (the) before the noun: 'de samme opgaver' = 'the same tasks'." },
      { surface: "meget", lemma: "meget", englishGloss: "much / a lot", partOfSpeech: "adverb", inflectionNote: "intensifier before comparatives: 'meget kortere' = 'much shorter'." },
      { surface: "glad", lemma: "glad", englishGloss: "happy", partOfSpeech: "adjective", inflectionNote: "base form, agrees with 'Peter' (common gender singular)." },
    ],
  },
  {
    passageId: "m2-t2-uddannelse-maria-modultest",
    englishSummary:
      "Maria wants to pass the modultest and hopes she can read Danish better within six months. Her teacher says she should practice every day to improve. Maria believes she can reach her goal if she works hard — she has a new test coming up soon.",
    words: [
      { surface: "vil", lemma: "ville", englishGloss: "wants to", partOfSpeech: "verb", inflectionNote: "present tense of the modal verb 'ville'; 'vil gerne' = 'would like to'." },
      { surface: "gerne", lemma: "gerne", englishGloss: "gladly / would like", partOfSpeech: "adverb", inflectionNote: "combines with 'vil' to soften a wish: 'vil gerne' = 'would like to'." },
      { surface: "bestå", lemma: "bestå", englishGloss: "pass (an exam)", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'vil' — Danish modals take a bare infinitive." },
      { surface: "modultesten", lemma: "modultest", englishGloss: "the modultest", partOfSpeech: "noun", inflectionNote: "definite singular: modultest → modultesten." },
      { surface: "håber", lemma: "håbe", englishGloss: "hopes", partOfSpeech: "verb", inflectionNote: "present tense of 'at håbe'." },
      { surface: "at", lemma: "at", englishGloss: "that", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause after verbs like 'håbe', 'sige', 'tro' (hope, say, believe)." },
      { surface: "kan", lemma: "kunne", englishGloss: "can", partOfSpeech: "verb", inflectionNote: "present tense of the modal verb 'kunne' (can/be able to)." },
      { surface: "bedre", lemma: "god", englishGloss: "better", partOfSpeech: "adjective/adverb", inflectionNote: "comparative of 'god' (good) — irregular comparative." },
      { surface: "halvt", lemma: "halv", englishGloss: "half", partOfSpeech: "adjective", inflectionNote: "neuter form of 'halv' (+t) to agree with 'år' (year)." },
      { surface: "hendes", lemma: "hendes", englishGloss: "her", partOfSpeech: "pronoun", inflectionNote: "possessive form of 'hun' (she), invariable before the noun." },
      { surface: "lærer", lemma: "lærer", englishGloss: "teacher", partOfSpeech: "noun", inflectionNote: "common gender: en lærer." },
      { surface: "siger", lemma: "sige", englishGloss: "says", partOfSpeech: "verb", inflectionNote: "present tense of 'at sige' — irregular." },
      { surface: "skal", lemma: "skulle", englishGloss: "should / must", partOfSpeech: "verb", inflectionNote: "present tense of the modal verb 'skulle' (shall/must)." },
      { surface: "øve", lemma: "øve", englishGloss: "practice", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'skal'; 'øve sig' = 'practice' (reflexive)." },
      { surface: "hver", lemma: "hver", englishGloss: "every / each", partOfSpeech: "pronoun", inflectionNote: "invariable before singular nouns: 'hver dag' = 'every day'." },
      { surface: "dag", lemma: "dag", englishGloss: "day", partOfSpeech: "noun", inflectionNote: "common gender: en dag." },
      { surface: "blive", lemma: "blive", englishGloss: "become", partOfSpeech: "verb", inflectionNote: "infinitive after 'for at' (in order to)." },
      { surface: "tror", lemma: "tro", englishGloss: "believes", partOfSpeech: "verb", inflectionNote: "present tense of 'at tro'." },
      { surface: "nå", lemma: "nå", englishGloss: "reach", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'kan'." },
      { surface: "mål", lemma: "mål", englishGloss: "goal", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "hvis", lemma: "hvis", englishGloss: "if", partOfSpeech: "conjunction", inflectionNote: "introduces a conditional subordinate clause." },
      { surface: "arbejder", lemma: "arbejde", englishGloss: "works", partOfSpeech: "verb", inflectionNote: "present tense of 'at arbejde'." },
      { surface: "hårdt", lemma: "hård", englishGloss: "hard", partOfSpeech: "adverb", inflectionNote: "adjective 'hård' + -t used adverbially (works hard)." },
      { surface: "skal", lemma: "skulle", englishGloss: "is going to", partOfSpeech: "verb", inflectionNote: "modal 'skal' used here to express a planned future event." },
      { surface: "snart", lemma: "snart", englishGloss: "soon", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "test", lemma: "test", englishGloss: "test", partOfSpeech: "noun", inflectionNote: "common gender: en test." },
      { surface: "hun", lemma: "hun", englishGloss: "she", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person singular feminine." },
      { surface: "læse", lemma: "læse", englishGloss: "read", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'kan'." },
      { surface: "dansk", lemma: "dansk", englishGloss: "Danish", partOfSpeech: "noun", inflectionNote: "the language name." },
      { surface: "sig", lemma: "sig", englishGloss: "herself", partOfSpeech: "pronoun", inflectionNote: "third-person reflexive pronoun, used in 'øve sig' (practice)." },
      { surface: "ny", lemma: "ny", englishGloss: "new", partOfSpeech: "adjective", inflectionNote: "base form, agrees with 'test' (common gender)." },
    ],
  },
  {
    passageId: "m2-t2-hverdagsliv-familien-flytter",
    englishSummary:
      "The Nielsen family used to live in a small apartment with a very small kitchen. They moved last summer to a bigger apartment, where they now sit around a big table for dinner. The kids were happy about their new rooms.",
    words: [
      { surface: "boede", lemma: "bo", englishGloss: "lived", partOfSpeech: "verb", inflectionNote: "past tense of 'at bo' — regular -ede ending." },
      { surface: "før", lemma: "før", englishGloss: "before / previously", partOfSpeech: "adverb", inflectionNote: "here an adverb meaning 'previously', not the conjunction." },
      { surface: "lille", lemma: "lille", englishGloss: "small", partOfSpeech: "adjective", inflectionNote: "singular common/neuter form of 'lille' — irregular, becomes 'små' in the plural." },
      { surface: "køkkenet", lemma: "køkken", englishGloss: "the kitchen", partOfSpeech: "noun", inflectionNote: "definite singular: køkken → køkkenet." },
      { surface: "var", lemma: "være", englishGloss: "was", partOfSpeech: "verb", inflectionNote: "past tense of 'at være'." },
      { surface: "meget", lemma: "meget", englishGloss: "very", partOfSpeech: "adverb", inflectionNote: "intensifier, does not inflect." },
      { surface: "når", lemma: "når", englishGloss: "when / whenever", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about a repeated or general time." },
      { surface: "lavede", lemma: "lave", englishGloss: "made / cooked", partOfSpeech: "verb", inflectionNote: "past tense of 'at lave' — regular -ede ending." },
      { surface: "stod", lemma: "stå", englishGloss: "stood", partOfSpeech: "verb", inflectionNote: "past tense of 'at stå' — irregular." },
      { surface: "tæt", lemma: "tæt", englishGloss: "close", partOfSpeech: "adjective/adverb", inflectionNote: "base form used adverbially: 'stod tæt' = 'stood close'." },
      { surface: "hinanden", lemma: "hinanden", englishGloss: "each other", partOfSpeech: "pronoun", inflectionNote: "reciprocal pronoun, invariable." },
      { surface: "flyttede", lemma: "flytte", englishGloss: "moved", partOfSpeech: "verb", inflectionNote: "past tense of 'at flytte' — regular -ede ending." },
      { surface: "sommer", lemma: "sommer", englishGloss: "summer", partOfSpeech: "noun", inflectionNote: "common gender: en sommer." },
      { surface: "større", lemma: "stor", englishGloss: "bigger", partOfSpeech: "adjective", inflectionNote: "comparative of 'stor' (big) — irregular stem change stor → stør- + -re." },
      { surface: "nu", lemma: "nu", englishGloss: "now", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "spiser", lemma: "spise", englishGloss: "eat", partOfSpeech: "verb", inflectionNote: "present tense of 'at spise' — used here in a 'nu, når...' present-habitual construction." },
      { surface: "aftensmad", lemma: "aftensmad", englishGloss: "dinner", partOfSpeech: "noun", inflectionNote: "compound: aften (evening) + mad (food)." },
      { surface: "sidder", lemma: "sidde", englishGloss: "sit", partOfSpeech: "verb", inflectionNote: "present tense of 'at sidde'." },
      { surface: "bord", lemma: "bord", englishGloss: "table", partOfSpeech: "noun", inflectionNote: "neuter: et bord." },
      { surface: "børnene", lemma: "barn", englishGloss: "the children", partOfSpeech: "noun", inflectionNote: "irregular plural+definite: barn → børn → børnene." },
      { surface: "glade", lemma: "glad", englishGloss: "happy", partOfSpeech: "adjective", inflectionNote: "plural form of 'glad' (+e) to agree with plural 'børnene'." },
      { surface: "værelser", lemma: "værelse", englishGloss: "rooms", partOfSpeech: "noun", inflectionNote: "plural of 'værelse' (+r)." },
      { surface: "familien", lemma: "familie", englishGloss: "the family", partOfSpeech: "noun", inflectionNote: "definite singular: familie → familien." },
      { surface: "lejlighed", lemma: "lejlighed", englishGloss: "apartment", partOfSpeech: "noun", inflectionNote: "common gender: en lejlighed." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "mad", lemma: "mad", englishGloss: "food", partOfSpeech: "noun", inflectionNote: "uncountable, no plural; 'lavede mad' = 'cooked'." },
      { surface: "sammen", lemma: "sammen", englishGloss: "together", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "sidste", lemma: "sidste", englishGloss: "last", partOfSpeech: "adjective", inflectionNote: "invariable form before a noun: 'sidste sommer' = 'last summer'." },
      { surface: "stort", lemma: "stor", englishGloss: "big", partOfSpeech: "adjective", inflectionNote: "neuter form of 'stor' (+t) to agree with neuter 'bord'." },
      { surface: "nye", lemma: "ny", englishGloss: "new", partOfSpeech: "adjective", inflectionNote: "plural form of 'ny' (+e) to agree with plural 'værelser'." },
    ],
  },
  {
    passageId: "m2-t2-medborgerskab-skat",
    englishSummary:
      "All citizens in Denmark pay tax, because it funds schools, hospitals and roads. People may speak their opinion publicly because Denmark has freedom of speech. New citizens should learn about Danish society and are encouraged to vote locally when they can — many see citizenship as taking responsibility.",
    words: [
      { surface: "alle", lemma: "alle", englishGloss: "all", partOfSpeech: "pronoun", inflectionNote: "plural quantifier before 'borgere'." },
      { surface: "borgere", lemma: "borger", englishGloss: "citizens", partOfSpeech: "noun", inflectionNote: "plural of 'borger' (+e)." },
      { surface: "skal", lemma: "skulle", englishGloss: "must", partOfSpeech: "verb", inflectionNote: "modal verb expressing obligation." },
      { surface: "betale", lemma: "betale", englishGloss: "pay", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'skal'." },
      { surface: "skat", lemma: "skat", englishGloss: "tax", partOfSpeech: "noun", inflectionNote: "common gender: en skat." },
      { surface: "skatten", lemma: "skat", englishGloss: "the tax", partOfSpeech: "noun", inflectionNote: "definite singular: skat → skatten." },
      { surface: "betaler", lemma: "betale", englishGloss: "pays for", partOfSpeech: "verb", inflectionNote: "present tense of 'at betale'." },
      { surface: "skoler", lemma: "skole", englishGloss: "schools", partOfSpeech: "noun", inflectionNote: "plural of 'skole' (+r)." },
      { surface: "hospitaler", lemma: "hospital", englishGloss: "hospitals", partOfSpeech: "noun", inflectionNote: "plural of 'hospital' (+er)." },
      { surface: "veje", lemma: "vej", englishGloss: "roads", partOfSpeech: "noun", inflectionNote: "plural of 'vej' (+e)." },
      { surface: "må", lemma: "måtte", englishGloss: "may / is allowed to", partOfSpeech: "verb", inflectionNote: "present tense of modal 'måtte'; 'må gerne' = 'is (positively) allowed to'." },
      { surface: "sige", lemma: "sige", englishGloss: "say / express", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'må'." },
      { surface: "mening", lemma: "mening", englishGloss: "opinion", partOfSpeech: "noun", inflectionNote: "common gender: en mening." },
      { surface: "offentligt", lemma: "offentlig", englishGloss: "publicly", partOfSpeech: "adverb", inflectionNote: "adjective 'offentlig' + -t used adverbially." },
      { surface: "ytringsfrihed", lemma: "ytringsfrihed", englishGloss: "freedom of speech", partOfSpeech: "noun", inflectionNote: "compound: ytring (expression/statement) + frihed (freedom)." },
      { surface: "nye", lemma: "ny", englishGloss: "new", partOfSpeech: "adjective", inflectionNote: "plural form of 'ny' (+e) to agree with plural 'borgere'." },
      { surface: "lære", lemma: "lære", englishGloss: "learn", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'skal'." },
      { surface: "samfund", lemma: "samfund", englishGloss: "society", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "bør", lemma: "burde", englishGloss: "should", partOfSpeech: "verb", inflectionNote: "present tense of the modal verb 'burde' (ought to)." },
      { surface: "deltage", lemma: "deltage", englishGloss: "participate", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'bør'." },
      { surface: "lokale", lemma: "lokal", englishGloss: "local", partOfSpeech: "adjective", inflectionNote: "plural form of 'lokal' (+e) to agree with plural 'valg'." },
      { surface: "valg", lemma: "valg", englishGloss: "elections", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "mulighed", lemma: "mulighed", englishGloss: "opportunity", partOfSpeech: "noun", inflectionNote: "common gender: en mulighed." },
      { surface: "mener", lemma: "mene", englishGloss: "think / believe", partOfSpeech: "verb", inflectionNote: "present tense of 'at mene'." },
      { surface: "medborgerskab", lemma: "medborgerskab", englishGloss: "citizenship", partOfSpeech: "noun", inflectionNote: "compound: med (fellow) + borger (citizen) + -skab (-ship)." },
      { surface: "handler", lemma: "handle", englishGloss: "is about", partOfSpeech: "verb", inflectionNote: "present tense of 'at handle om' (to be about)." },
      { surface: "tage", lemma: "tage", englishGloss: "take", partOfSpeech: "verb", inflectionNote: "infinitive after 'at' (to)." },
      { surface: "ansvar", lemma: "ansvar", englishGloss: "responsibility", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
      { surface: "danmark", lemma: "Danmark", englishGloss: "Denmark", partOfSpeech: "proper noun", inflectionNote: "country name, does not inflect." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "man", lemma: "man", englishGloss: "one / you (general)", partOfSpeech: "pronoun", inflectionNote: "impersonal pronoun for general statements." },
      { surface: "sin", lemma: "sin", englishGloss: "one's (own)", partOfSpeech: "pronoun", inflectionNote: "reflexive possessive, common-gender form, agrees with 'mening' (en-word)." },
      { surface: "har", lemma: "have", englishGloss: "has", partOfSpeech: "verb", inflectionNote: "present tense of 'at have'." },
      { surface: "det", lemma: "det", englishGloss: "it", partOfSpeech: "pronoun", inflectionNote: "neuter subject pronoun, impersonal 'det er vigtigt' (it's important)." },
      { surface: "danske", lemma: "dansk", englishGloss: "Danish", partOfSpeech: "adjective", inflectionNote: "definite form of 'dansk' (+e) after 'det': 'det danske samfund'." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "når", lemma: "når", englishGloss: "when / whenever", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about a repeated or general time." },
      { surface: "mange", lemma: "mange", englishGloss: "many", partOfSpeech: "pronoun", inflectionNote: "plural quantifier used as subject here ('mange mener')." },
      { surface: "at", lemma: "at", englishGloss: "that", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause after 'mener' (thinks)." },
    ],
  },
  {
    passageId: "m2-t3-arbejde-hospital-passiv",
    englishSummary:
      "At the hospital, patients are examined by a doctor before being admitted. Hygiene rules are strictly followed because otherwise infection risk rises. There aren't enough nurses right now, so many shifts are covered by temps — management has decided to hire more permanent staff next year.",
    words: [
      { surface: "bliver", lemma: "blive", englishGloss: "is / are (being)", partOfSpeech: "verb", inflectionNote: "present tense of 'at blive', used with a past participle to form the passive voice: 'bliver undersøgt' = 'is examined'." },
      { surface: "undersøgt", lemma: "undersøge", englishGloss: "examined", partOfSpeech: "verb", inflectionNote: "past participle of 'at undersøge', used with 'bliver' to form the passive." },
      { surface: "læge", lemma: "læge", englishGloss: "a doctor", partOfSpeech: "noun", inflectionNote: "common gender: en læge." },
      { surface: "indlagt", lemma: "indlægge", englishGloss: "admitted", partOfSpeech: "verb", inflectionNote: "past participle of 'at indlægge' (to admit to hospital), passive with 'bliver'." },
      { surface: "reglerne", lemma: "regel", englishGloss: "the rules", partOfSpeech: "noun", inflectionNote: "irregular definite plural: regel → regler (plural) → reglerne." },
      { surface: "hygiejne", lemma: "hygiejne", englishGloss: "hygiene", partOfSpeech: "noun", inflectionNote: "common gender, uncountable." },
      { surface: "overholdes", lemma: "overholde", englishGloss: "is followed / is observed", partOfSpeech: "verb", inflectionNote: "-s passive of 'at overholde' — an alternative passive form to 'bliver + participle', common in formal writing." },
      { surface: "strengt", lemma: "streng", englishGloss: "strictly", partOfSpeech: "adverb", inflectionNote: "adjective 'streng' + -t used adverbially." },
      { surface: "personale", lemma: "personale", englishGloss: "staff", partOfSpeech: "noun", inflectionNote: "neuter, collective noun, no plural." },
      { surface: "risikoen", lemma: "risiko", englishGloss: "the risk", partOfSpeech: "noun", inflectionNote: "definite singular: risiko → risikoen." },
      { surface: "infektioner", lemma: "infektion", englishGloss: "infections", partOfSpeech: "noun", inflectionNote: "plural of 'infektion' (+er)." },
      { surface: "ellers", lemma: "ellers", englishGloss: "otherwise", partOfSpeech: "adverb", inflectionNote: "does not inflect." },
      { surface: "stiger", lemma: "stige", englishGloss: "rises", partOfSpeech: "verb", inflectionNote: "present tense of 'at stige'." },
      { surface: "for", lemma: "for", englishGloss: "too", partOfSpeech: "adverb", inflectionNote: "here 'for få' = 'too few', not the preposition 'for'." },
      { surface: "få", lemma: "få", englishGloss: "few", partOfSpeech: "adjective", inflectionNote: "plural quantifier meaning 'few', agrees with plural 'sygeplejersker'." },
      { surface: "sygeplejersker", lemma: "sygeplejerske", englishGloss: "nurses", partOfSpeech: "noun", inflectionNote: "plural of 'sygeplejerske' (+r)." },
      { surface: "øjeblikket", lemma: "øjeblik", englishGloss: "the moment", partOfSpeech: "noun", inflectionNote: "definite singular: øjeblik → øjeblikket; 'i øjeblikket' = 'currently'." },
      { surface: "derfor", lemma: "derfor", englishGloss: "therefore", partOfSpeech: "adverb", inflectionNote: "connector showing a consequence of what was just said; triggers verb-subject inversion when first in the clause." },
      { surface: "vagter", lemma: "vagt", englishGloss: "shifts", partOfSpeech: "noun", inflectionNote: "plural of 'vagt' (+er)." },
      { surface: "dækket", lemma: "dække", englishGloss: "covered", partOfSpeech: "verb", inflectionNote: "past participle of 'at dække', passive with 'bliver'." },
      { surface: "vikarer", lemma: "vikar", englishGloss: "temps / substitutes", partOfSpeech: "noun", inflectionNote: "plural of 'vikar' (+er)." },
      { surface: "ledelsen", lemma: "ledelse", englishGloss: "management", partOfSpeech: "noun", inflectionNote: "definite singular: ledelse → ledelsen." },
      { surface: "besluttet", lemma: "beslutte", englishGloss: "decided", partOfSpeech: "verb", inflectionNote: "past participle of 'at beslutte', used with 'har' to form present perfect: 'har besluttet' = 'has decided'." },
      { surface: "ansætte", lemma: "ansætte", englishGloss: "hire", partOfSpeech: "verb", inflectionNote: "infinitive after 'at' (to)." },
      { surface: "flere", lemma: "mange", englishGloss: "more", partOfSpeech: "adjective", inflectionNote: "comparative of 'mange' (many)." },
      { surface: "fastansatte", lemma: "fastansat", englishGloss: "permanent employees", partOfSpeech: "noun/adjective", inflectionNote: "compound adjective (fast = fixed + ansat = employed) used as a plural noun here." },
      { surface: "hospitalet", lemma: "hospital", englishGloss: "the hospital", partOfSpeech: "noun", inflectionNote: "definite singular: hospital → hospitalet." },
      { surface: "patienterne", lemma: "patient", englishGloss: "the patients", partOfSpeech: "noun", inflectionNote: "definite plural: patient → patienter → patienterne." },
      { surface: "af", lemma: "af", englishGloss: "by", partOfSpeech: "preposition", inflectionNote: "introduces the agent (the 'doer') in a passive sentence: 'undersøgt af en læge' = 'examined by a doctor'." },
      { surface: "før", lemma: "før", englishGloss: "before", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about time." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "alt", lemma: "al", englishGloss: "all", partOfSpeech: "pronoun", inflectionNote: "neuter form of 'al', agrees with 'personale' (neuter, uncountable)." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason." },
      { surface: "er", lemma: "være", englishGloss: "are", partOfSpeech: "verb", inflectionNote: "present tense of 'at være'; 'der er for få' = 'there are too few'." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "har", lemma: "have", englishGloss: "has", partOfSpeech: "verb", inflectionNote: "present tense of 'at have', part of the present perfect 'har besluttet' (has decided)." },
      { surface: "at", lemma: "at", englishGloss: "to", partOfSpeech: "particle", inflectionNote: "infinitive marker before 'ansætte' (to hire)." },
      { surface: "det", lemma: "det", englishGloss: "the next", partOfSpeech: "pronoun", inflectionNote: "used with 'næste' before neuter 'år': 'i det næste år'." },
      { surface: "næste", lemma: "næste", englishGloss: "next", partOfSpeech: "adjective", inflectionNote: "invariable form used before a noun." },
      { surface: "år", lemma: "år", englishGloss: "year", partOfSpeech: "noun", inflectionNote: "neuter, same form singular and plural." },
    ],
  },
  {
    passageId: "m2-t3-uddannelse-maria-grammatik",
    englishSummary:
      "Even though Maria finds grammar difficult, she practices every day because she knows it helps her improve. Her teacher explains that you learn best when you both listen and speak. Even though some students are nervous about speaking in front of the class, the teacher says it's the best way to learn.",
    words: [
      { surface: "selvom", lemma: "selvom", englishGloss: "even though / although", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause of concession — the main clause states something true despite it." },
      { surface: "synes", lemma: "synes", englishGloss: "thinks / finds", partOfSpeech: "verb", inflectionNote: "present tense of 'at synes' (to have an opinion) — same form as infinitive, ends in -s." },
      { surface: "grammatik", lemma: "grammatik", englishGloss: "grammar", partOfSpeech: "noun", inflectionNote: "common gender: en grammatik." },
      { surface: "svær", lemma: "svær", englishGloss: "difficult", partOfSpeech: "adjective", inflectionNote: "base form, agrees with 'grammatik' (common gender)." },
      { surface: "øver", lemma: "øve", englishGloss: "practices", partOfSpeech: "verb", inflectionNote: "present tense of 'at øve sig' (reflexive)." },
      { surface: "ved", lemma: "vide", englishGloss: "knows", partOfSpeech: "verb", inflectionNote: "present tense of 'at vide' (to know a fact) — irregular." },
      { surface: "hjælper", lemma: "hjælpe", englishGloss: "helps", partOfSpeech: "verb", inflectionNote: "present tense of 'at hjælpe'." },
      { surface: "blive", lemma: "blive", englishGloss: "become", partOfSpeech: "verb", inflectionNote: "infinitive after 'til at' (to)." },
      { surface: "forklarer", lemma: "forklare", englishGloss: "explains", partOfSpeech: "verb", inflectionNote: "present tense of 'at forklare'." },
      { surface: "man", lemma: "man", englishGloss: "one / you (general)", partOfSpeech: "pronoun", inflectionNote: "impersonal pronoun used for general statements, like English generic 'you' or 'one'." },
      { surface: "lærer", lemma: "lære", englishGloss: "learns", partOfSpeech: "verb", inflectionNote: "present tense of 'at lære' (to learn) — note: identical spelling to the noun 'lærer' (teacher), distinguished by context." },
      { surface: "mest", lemma: "meget", englishGloss: "most", partOfSpeech: "adverb", inflectionNote: "superlative of 'meget' (much) — irregular." },
      { surface: "både", lemma: "både", englishGloss: "both", partOfSpeech: "conjunction", inflectionNote: "pairs with 'og': 'både...og' = 'both...and'." },
      { surface: "lytter", lemma: "lytte", englishGloss: "listens", partOfSpeech: "verb", inflectionNote: "present tense of 'at lytte'." },
      { surface: "taler", lemma: "tale", englishGloss: "speaks", partOfSpeech: "verb", inflectionNote: "present tense of 'at tale'." },
      { surface: "nogle", lemma: "nogle", englishGloss: "some", partOfSpeech: "pronoun", inflectionNote: "plural quantifier before 'elever'." },
      { surface: "nervøse", lemma: "nervøs", englishGloss: "nervous", partOfSpeech: "adjective", inflectionNote: "plural form of 'nervøs' (+e) to agree with plural 'elever'." },
      { surface: "foran", lemma: "foran", englishGloss: "in front of", partOfSpeech: "preposition", inflectionNote: "does not inflect." },
      { surface: "klassen", lemma: "klasse", englishGloss: "the class", partOfSpeech: "noun", inflectionNote: "definite singular: klasse → klassen." },
      { surface: "siger", lemma: "sige", englishGloss: "says", partOfSpeech: "verb", inflectionNote: "present tense of 'at sige'." },
      { surface: "bedste", lemma: "god", englishGloss: "best", partOfSpeech: "adjective", inflectionNote: "superlative definite form of 'god' (good) — irregular: god → bedre → bedst → den bedste." },
      { surface: "måde", lemma: "måde", englishGloss: "way", partOfSpeech: "noun", inflectionNote: "common gender: en måde; 'på' = 'to' in 'måde at lære på'." },
      { surface: "maria", lemma: "Maria", englishGloss: "Maria", partOfSpeech: "proper noun", inflectionNote: "name, does not inflect." },
      { surface: "er", lemma: "være", englishGloss: "is", partOfSpeech: "verb", inflectionNote: "present tense of 'at være'." },
      { surface: "hun", lemma: "hun", englishGloss: "she", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person singular feminine." },
      { surface: "sig", lemma: "sig", englishGloss: "herself", partOfSpeech: "pronoun", inflectionNote: "third-person reflexive pronoun, used in 'øver sig' (practices)." },
      { surface: "hver", lemma: "hver", englishGloss: "every / each", partOfSpeech: "pronoun", inflectionNote: "invariable before singular nouns: 'hver dag' = 'every day'." },
      { surface: "dag", lemma: "dag", englishGloss: "day", partOfSpeech: "noun", inflectionNote: "common gender: en dag." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason." },
      { surface: "det", lemma: "det", englishGloss: "it", partOfSpeech: "pronoun", inflectionNote: "neuter pronoun referring back to 'grammatik'." },
      { surface: "hende", lemma: "hun", englishGloss: "her", partOfSpeech: "pronoun", inflectionNote: "object form of 'hun' (she)." },
      { surface: "til", lemma: "til", englishGloss: "to", partOfSpeech: "preposition", inflectionNote: "does not inflect." },
      { surface: "bedre", lemma: "god", englishGloss: "better", partOfSpeech: "adjective", inflectionNote: "comparative of 'god' (good) — irregular." },
      { surface: "hendes", lemma: "hendes", englishGloss: "her", partOfSpeech: "pronoun", inflectionNote: "possessive form of 'hun' (she), invariable before the noun." },
      { surface: "når", lemma: "når", englishGloss: "when", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about a repeated/general time." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "elever", lemma: "elev", englishGloss: "students", partOfSpeech: "noun", inflectionNote: "plural of 'elev' (+er)." },
      { surface: "tale", lemma: "tale", englishGloss: "speak", partOfSpeech: "verb", inflectionNote: "infinitive after 'at' (to)." },
      { surface: "læreren", lemma: "lærer", englishGloss: "the teacher", partOfSpeech: "noun", inflectionNote: "definite singular: lærer → læreren." },
      { surface: "den", lemma: "den", englishGloss: "the", partOfSpeech: "article/pronoun", inflectionNote: "common-gender definite article, used with 'bedste' before 'måde' (en-word)." },
      { surface: "lære", lemma: "lære", englishGloss: "learn", partOfSpeech: "verb", inflectionNote: "infinitive after 'at' (to)." },
    ],
  },
  {
    passageId: "m2-t3-hverdagsliv-lejlighed-flytning",
    englishSummary:
      "The new apartment is being painted by a painting company before the family moves in. The furniture will be moved next week by a moving company. Everything is turning out more expensive than the family expected, but they're happy about the new place because it's close to the kids' school.",
    words: [
      { surface: "nye", lemma: "ny", englishGloss: "new", partOfSpeech: "adjective", inflectionNote: "definite form of 'ny' (+e), required after 'den' in 'den nye lejlighed'." },
      { surface: "bliver", lemma: "blive", englishGloss: "is (being)", partOfSpeech: "verb", inflectionNote: "present tense of 'at blive', forming the passive with a past participle: 'bliver malet' = 'is being painted'." },
      { surface: "malet", lemma: "male", englishGloss: "painted", partOfSpeech: "verb", inflectionNote: "past participle of 'at male', used with 'bliver' to form the passive." },
      { surface: "malerfirma", lemma: "malerfirma", englishGloss: "painting company", partOfSpeech: "noun", inflectionNote: "compound: maler (painter) + firma (company), neuter." },
      { surface: "flytter", lemma: "flytte", englishGloss: "moves", partOfSpeech: "verb", inflectionNote: "present tense of 'at flytte'; 'flytter ind' = 'moves in'." },
      { surface: "møblerne", lemma: "møbel", englishGloss: "the furniture", partOfSpeech: "noun", inflectionNote: "irregular definite plural: møbel → møbler (plural) → møblerne." },
      { surface: "kørt", lemma: "køre", englishGloss: "driven / transported", partOfSpeech: "verb", inflectionNote: "past participle of 'at køre', used with 'bliver' to form the passive." },
      { surface: "derhen", lemma: "derhen", englishGloss: "there (to that place)", partOfSpeech: "adverb", inflectionNote: "directional adverb — 'to there', paired with motion verbs." },
      { surface: "flyttefirma", lemma: "flyttefirma", englishGloss: "moving company", partOfSpeech: "noun", inflectionNote: "compound: flytte (move) + firma (company), neuter." },
      { surface: "uge", lemma: "uge", englishGloss: "week", partOfSpeech: "noun", inflectionNote: "common gender: en uge; 'i næste uge' = 'next week'." },
      { surface: "dyrere", lemma: "dyr", englishGloss: "more expensive", partOfSpeech: "adjective", inflectionNote: "comparative of 'dyr' (expensive) — add -ere." },
      { surface: "end", lemma: "end", englishGloss: "than", partOfSpeech: "conjunction", inflectionNote: "used after a comparative to introduce the comparison." },
      { surface: "havde", lemma: "have", englishGloss: "had", partOfSpeech: "verb", inflectionNote: "past tense of 'at have', part of the past perfect 'havde regnet med' (had expected)." },
      { surface: "regnet", lemma: "regne", englishGloss: "expected / reckoned", partOfSpeech: "verb", inflectionNote: "past participle of 'at regne med' (to expect/reckon with)." },
      { surface: "dog", lemma: "dog", englishGloss: "however / still", partOfSpeech: "adverb", inflectionNote: "signals a mild contrast with what was just said — 'even so'." },
      { surface: "glade", lemma: "glad", englishGloss: "happy", partOfSpeech: "adjective", inflectionNote: "plural form of 'glad' (+e), agrees with plural subject 'de' (they)." },
      { surface: "ligger", lemma: "ligge", englishGloss: "is located", partOfSpeech: "verb", inflectionNote: "present tense of 'at ligge' (to lie/be situated)." },
      { surface: "børnenes", lemma: "barn", englishGloss: "the children's", partOfSpeech: "noun", inflectionNote: "genitive of the definite plural 'børnene' (+s): børnenes skole = 'the children's school'." },
      { surface: "den", lemma: "den", englishGloss: "the", partOfSpeech: "article", inflectionNote: "common-gender definite article used before an adjective + noun: 'den nye lejlighed'." },
      { surface: "lejlighed", lemma: "lejlighed", englishGloss: "apartment", partOfSpeech: "noun", inflectionNote: "common gender: en lejlighed." },
      { surface: "af", lemma: "af", englishGloss: "by", partOfSpeech: "preposition", inflectionNote: "introduces the agent in a passive sentence: 'malet af et malerfirma' = 'painted by a painting company'." },
      { surface: "før", lemma: "før", englishGloss: "before", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about time." },
      { surface: "familien", lemma: "familie", englishGloss: "the family", partOfSpeech: "noun", inflectionNote: "definite singular: familie → familien." },
      { surface: "ind", lemma: "ind", englishGloss: "in", partOfSpeech: "adverb", inflectionNote: "directional particle with 'flytter': 'flytter ind' = 'moves in'." },
      { surface: "uge", lemma: "uge", englishGloss: "week", partOfSpeech: "noun", inflectionNote: "common gender: en uge; 'næste uge' = 'next week'." },
      { surface: "det", lemma: "det", englishGloss: "it", partOfSpeech: "pronoun", inflectionNote: "neuter pronoun, impersonal subject in 'det hele' (the whole thing)." },
      { surface: "hele", lemma: "hel", englishGloss: "whole", partOfSpeech: "adjective", inflectionNote: "definite form of 'hel' (+e) after 'det': 'det hele' = 'the whole thing'." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "er", lemma: "være", englishGloss: "are", partOfSpeech: "verb", inflectionNote: "present tense of 'at være'." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason." },
      { surface: "tæt", lemma: "tæt", englishGloss: "close", partOfSpeech: "adjective", inflectionNote: "base form used adverbially: 'ligger tæt på' = 'is located close to'." },
      { surface: "skole", lemma: "skole", englishGloss: "school", partOfSpeech: "noun", inflectionNote: "common gender: en skole." },
    ],
  },
  {
    passageId: "m2-t3-medborgerskab-nye-borgere",
    englishSummary:
      "Even though many new citizens find the Danish system hard to understand at first, most get better at it after living in the country a few years. The municipality offers courses on rights and duties, because it's important everyone understands how society works. Even though the courses are voluntary, many attend because they want to understand their new home country better.",
    words: [
      { surface: "selvom", lemma: "selvom", englishGloss: "even though / although", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause of concession." },
      { surface: "synes", lemma: "synes", englishGloss: "find / think", partOfSpeech: "verb", inflectionNote: "present tense of 'at synes' — ends in -s in all forms." },
      { surface: "system", lemma: "system", englishGloss: "system", partOfSpeech: "noun", inflectionNote: "neuter: et system." },
      { surface: "svært", lemma: "svær", englishGloss: "difficult", partOfSpeech: "adjective", inflectionNote: "neuter form of 'svær' (+t) to agree with neuter 'system'." },
      { surface: "forstå", lemma: "forstå", englishGloss: "understand", partOfSpeech: "verb", inflectionNote: "infinitive after 'at' (to)." },
      { surface: "starten", lemma: "start", englishGloss: "the start", partOfSpeech: "noun", inflectionNote: "definite singular: start → starten; 'i starten' = 'at first'." },
      { surface: "fleste", lemma: "mange", englishGloss: "most", partOfSpeech: "adjective", inflectionNote: "superlative definite form of 'mange' (many): mange → flere → flest → de fleste." },
      { surface: "boet", lemma: "bo", englishGloss: "lived", partOfSpeech: "verb", inflectionNote: "past participle of 'at bo', used with 'har' for present perfect: 'har boet' = 'have lived'." },
      { surface: "landet", lemma: "land", englishGloss: "the country", partOfSpeech: "noun", inflectionNote: "definite singular: land → landet." },
      { surface: "nogle", lemma: "nogle", englishGloss: "some / a few", partOfSpeech: "pronoun", inflectionNote: "quantifier before plural 'år'." },
      { surface: "kommunen", lemma: "kommune", englishGloss: "the municipality", partOfSpeech: "noun", inflectionNote: "definite singular: kommune → kommunen." },
      { surface: "tilbyder", lemma: "tilbyde", englishGloss: "offers", partOfSpeech: "verb", inflectionNote: "present tense of 'at tilbyde'." },
      { surface: "kurser", lemma: "kursus", englishGloss: "courses", partOfSpeech: "noun", inflectionNote: "irregular plural of 'kursus' (kursus → kurser)." },
      { surface: "hvor", lemma: "hvor", englishGloss: "where", partOfSpeech: "conjunction", inflectionNote: "introduces a relative clause referring back to 'kurser'." },
      { surface: "rettigheder", lemma: "rettighed", englishGloss: "rights", partOfSpeech: "noun", inflectionNote: "plural of 'rettighed' (+er)." },
      { surface: "pligter", lemma: "pligt", englishGloss: "duties", partOfSpeech: "noun", inflectionNote: "plural of 'pligt' (+er)." },
      { surface: "vigtigt", lemma: "vigtig", englishGloss: "important", partOfSpeech: "adjective", inflectionNote: "neuter form of 'vigtig' (+t), agrees with the impersonal 'det' subject." },
      { surface: "alle", lemma: "alle", englishGloss: "everyone", partOfSpeech: "pronoun", inflectionNote: "used here as subject meaning 'everyone'." },
      { surface: "forstår", lemma: "forstå", englishGloss: "understands", partOfSpeech: "verb", inflectionNote: "present tense of 'at forstå'." },
      { surface: "hvordan", lemma: "hvordan", englishGloss: "how", partOfSpeech: "conjunction", inflectionNote: "introduces an indirect question / subordinate clause." },
      { surface: "samfundet", lemma: "samfund", englishGloss: "society", partOfSpeech: "noun", inflectionNote: "definite singular: samfund → samfundet." },
      { surface: "fungerer", lemma: "fungere", englishGloss: "works / functions", partOfSpeech: "verb", inflectionNote: "present tense of 'at fungere'." },
      { surface: "kurserne", lemma: "kursus", englishGloss: "the courses", partOfSpeech: "noun", inflectionNote: "definite plural: kursus → kurser (plural) → kurserne (definite plural)." },
      { surface: "frivillige", lemma: "frivillig", englishGloss: "voluntary", partOfSpeech: "adjective", inflectionNote: "plural form of 'frivillig' (+e), agrees with plural 'kurserne'." },
      { surface: "deltager", lemma: "deltage", englishGloss: "attend / participate", partOfSpeech: "verb", inflectionNote: "present tense of 'at deltage'." },
      { surface: "vil", lemma: "ville", englishGloss: "want to", partOfSpeech: "verb", inflectionNote: "present tense of modal 'ville'; 'vil gerne' = 'would like to'." },
      { surface: "hjemland", lemma: "hjemland", englishGloss: "home country", partOfSpeech: "noun", inflectionNote: "compound: hjem (home) + land (country), neuter." },
      { surface: "bedre", lemma: "god", englishGloss: "better", partOfSpeech: "adverb", inflectionNote: "comparative of 'god'/'godt' used adverbially: 'forstå bedre' = 'understand better'." },
      { surface: "mange", lemma: "mange", englishGloss: "many", partOfSpeech: "pronoun", inflectionNote: "plural quantifier before plural nouns." },
      { surface: "nye", lemma: "ny", englishGloss: "new", partOfSpeech: "adjective", inflectionNote: "plural form of 'ny' (+e) to agree with plural 'borgere'." },
      { surface: "borgere", lemma: "borger", englishGloss: "citizens", partOfSpeech: "noun", inflectionNote: "plural of 'borger' (+e)." },
      { surface: "at", lemma: "at", englishGloss: "that", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause after 'synes' (finds/thinks)." },
      { surface: "det", lemma: "det", englishGloss: "it", partOfSpeech: "pronoun", inflectionNote: "neuter pronoun, impersonal subject 'det er vigtigt' (it's important)." },
      { surface: "danske", lemma: "dansk", englishGloss: "Danish", partOfSpeech: "adjective", inflectionNote: "definite form of 'dansk' (+e) after 'det': 'det danske system'." },
      { surface: "er", lemma: "være", englishGloss: "is / are", partOfSpeech: "verb", inflectionNote: "present tense of 'at være'." },
      { surface: "bliver", lemma: "blive", englishGloss: "become", partOfSpeech: "verb", inflectionNote: "present tense of 'at blive' (to become)." },
      { surface: "de", lemma: "de", englishGloss: "they", partOfSpeech: "pronoun", inflectionNote: "subject pronoun, third-person plural." },
      { surface: "til", lemma: "til", englishGloss: "to / at", partOfSpeech: "preposition", inflectionNote: "does not inflect; 'bedre til det' = 'better at it'." },
      { surface: "når", lemma: "når", englishGloss: "when", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause about a repeated/general time." },
      { surface: "har", lemma: "have", englishGloss: "have", partOfSpeech: "verb", inflectionNote: "present tense of 'at have', part of present perfect 'har boet' (have lived)." },
      { surface: "man", lemma: "man", englishGloss: "one / you (general)", partOfSpeech: "pronoun", inflectionNote: "impersonal pronoun for general statements." },
      { surface: "kan", lemma: "kunne", englishGloss: "can", partOfSpeech: "verb", inflectionNote: "present tense of the modal verb 'kunne' (can)." },
      { surface: "lære", lemma: "lære", englishGloss: "learn", partOfSpeech: "verb", inflectionNote: "infinitive after modal 'kan'." },
      { surface: "og", lemma: "og", englishGloss: "and", partOfSpeech: "conjunction", inflectionNote: "coordinates two clauses or items of equal weight." },
      { surface: "fordi", lemma: "fordi", englishGloss: "because", partOfSpeech: "conjunction", inflectionNote: "introduces a subordinate clause giving a reason." },
      { surface: "gerne", lemma: "gerne", englishGloss: "gladly / would like", partOfSpeech: "adverb", inflectionNote: "combines with 'vil' to soften a wish: 'vil gerne' = 'would like to'." },
      { surface: "deres", lemma: "deres", englishGloss: "their", partOfSpeech: "pronoun", inflectionNote: "possessive form of 'de' (they), invariable before the noun." },
    ],
  },
];

export const GLOSSARY_BY_PASSAGE_ID = new Map(MODUL2_GLOSSARIES.map((g) => [g.passageId, g]));
