import type { DanishVerb, VerbTheme } from "@/types";

// The 500 most common Danish verbs.
//
// In code rather than in a table for the same reason the reading library is:
// it is content that ships with the app and is identical for every learner, so
// a table would add a migration, a seed script and a failure mode without
// adding a single thing the import does not already give — including type
// checking, which catches a missing conjugation at build time.
//
// WHAT EACH ENTRY CARRIES, and why:
//
//   the four forms   infinitive / present / past / perfect. Danish needs no
//                    person agreement, so these four ARE the conjugation.
//   the auxiliary    "er" for motion and change of state (jeg er gået), "har"
//                    otherwise. Getting this wrong is one of the most common
//                    learner mistakes and no table of endings prevents it.
//   the group        which regular class it belongs to, or 3 for strong verbs.
//                    Knowing the group generalises; memorising forms does not.
//   an example       one real sentence, with its English. A verb without a
//                    sentence is a flashcard, and flashcards do not transfer.
//   usage            the preposition or fixed expression it lives in. "at
//                    glæde sig TIL", "at tage AF STED" — the part a dictionary
//                    gloss leaves out and the learner needs most.
//
// The builders below exist so that the regular verbs — the great majority —
// state only what actually varies. `r1` and `r2` derive the forms from the
// class rule, so a typo in a predictable form is impossible; `irr` spells
// every form out, which is exactly right for the verbs that have to be
// learned one at a time.

let nextRank = 0;

/** Stem for a regular verb: the infinitive without its final -e. */
const stem = (infinitive: string): string => {
  return infinitive.endsWith("e") ? infinitive.slice(0, -1) : infinitive;
};

interface Extra {
  aux?: "har" | "er";
  usage?: string;
  imperative?: string;
}

/**
 * Group 1: -er / -ede / -et. The class a Danish verb belongs to unless it is
 * known not to, and the one every new or borrowed verb joins (at google →
 * googlede).
 */
const r1 = (
  infinitive: string,
  english: string,
  example: string,
  exampleEnglish: string,
  themes: VerbTheme[],
  extra: Extra = {}
): DanishVerb => {
  const s = stem(infinitive);
  // A verb whose infinitive has no final -e (bo, tro, ske) keeps the whole
  // word and just adds the ending: bor / boede / boet.
  const base = infinitive.endsWith("e") ? s : infinitive;
  return {
    infinitive,
    english,
    present: base + (infinitive.endsWith("e") ? "er" : "r"),
    past: base + "ede",
    perfect: base + "et",
    auxiliary: extra.aux ?? "har",
    group: 1,
    imperative: extra.imperative ?? base,
    example,
    exampleEnglish,
    themes,
    rank: ++nextRank,
    usage: extra.usage,
  };
};

/** Group 2: -er / -te / -t. Used where the stem ends in a consonant. */
const r2 = (
  infinitive: string,
  english: string,
  example: string,
  exampleEnglish: string,
  themes: VerbTheme[],
  extra: Extra = {}
): DanishVerb => {
  const s = stem(infinitive);
  return {
    infinitive,
    english,
    present: s + "er",
    past: s + "te",
    perfect: s + "t",
    auxiliary: extra.aux ?? "har",
    group: 2,
    imperative: extra.imperative ?? s,
    example,
    exampleEnglish,
    themes,
    rank: ++nextRank,
    usage: extra.usage,
  };
};

/** Strong and irregular verbs — every form spelled out, because none follows. */
const irr = (
  infinitive: string,
  english: string,
  present: string,
  past: string,
  perfect: string,
  example: string,
  exampleEnglish: string,
  themes: VerbTheme[],
  extra: Extra = {}
): DanishVerb => {
  return {
    infinitive,
    english,
    present,
    past,
    perfect,
    auxiliary: extra.aux ?? "har",
    group: 3,
    imperative: extra.imperative ?? stem(infinitive),
    example,
    exampleEnglish,
    themes,
    rank: ++nextRank,
    usage: extra.usage,
  };
};

export const VERBS: DanishVerb[] = [
  // --- 1-25: the verbs everything else is built on ------------------------
  irr("være", "be", "er", "var", "været", "Jeg er træt i dag.", "I am tired today.", ["core"], { aux: "har", imperative: "vær", usage: "'er' is the same for every person: jeg/du/han/vi er." }),
  irr("have", "have", "har", "havde", "haft", "Vi har to børn.", "We have two children.", ["core"], { imperative: "hav", usage: "Also the auxiliary for the perfect: jeg har spist." }),
  irr("kunne", "can / be able to", "kan", "kunne", "kunnet", "Jeg kan tale lidt dansk.", "I can speak a little Danish.", ["core"], { usage: "Modal: the next verb follows in the bare infinitive, with no 'at' — kan tale, never 'kan at tale'." }),
  irr("skulle", "shall / be going to", "skal", "skulle", "skullet", "Jeg skal på arbejde klokken syv.", "I have to be at work at seven.", ["core"], { usage: "Obligation and arrangements. 'Jeg skal i byen' = I'm going into town — no verb of motion needed." }),
  irr("ville", "will / want to", "vil", "ville", "villet", "Hun vil gerne lære dansk.", "She would like to learn Danish.", ["core"], { usage: "'vil gerne' is how you say 'would like'; 'vil' alone can sound like a demand." }),
  irr("måtte", "may / must", "må", "måtte", "måttet", "Du må godt sidde her.", "You're allowed to sit here.", ["core"], { usage: "'må godt' = are allowed to; 'må ikke' = must not. The 'godt' is what separates permission from obligation." }),
  irr("blive", "become / stay", "bliver", "blev", "blevet", "Det bliver koldt i aften.", "It's going to be cold tonight.", ["core", "change"], { aux: "er", usage: "Three jobs: become, stay, and the passive (huset bliver malet = the house is being painted)." }),
  irr("komme", "come", "kommer", "kom", "kommet", "Hun kommer fra Polen.", "She comes from Poland.", ["core", "movement"], { aux: "er", usage: "'komme fra' = be from; 'komme til at' = end up doing / happen to." }),
  irr("få", "get / receive", "får", "fik", "fået", "Jeg fik et brev fra kommunen.", "I got a letter from the municipality.", ["core"], { usage: "Also 'get something done': jeg fik ryddet op." }),
  irr("gå", "walk / go", "går", "gik", "gået", "Vi går i skole hver dag.", "We go to school every day.", ["core", "movement"], { aux: "er", usage: "On foot. For a bus or car use 'køre'. 'Hvordan går det?' = How's it going?" }),
  irr("se", "see", "ser", "så", "set", "Jeg så en film i går.", "I saw a film yesterday.", ["core", "thinking"], { usage: "'se på' = look at; 'se ud' = look/appear (hun ser glad ud)." }),
  irr("sige", "say", "siger", "sagde", "sagt", "Hun sagde ikke noget.", "She didn't say anything.", ["core", "communication"], { usage: "'sagde' is pronounced 'sa' — the -gd- is silent." }),
  irr("tage", "take", "tager", "tog", "taget", "Jeg tager bussen til arbejde.", "I take the bus to work.", ["core", "movement"], { usage: "'tage af sted' = set off; 'tage sig af' = look after." }),
  irr("give", "give", "giver", "gav", "givet", "Han gav mig en god idé.", "He gave me a good idea.", ["core"], { usage: "Person first, thing second: giver mig en bog." }),
  irr("gøre", "do / make", "gør", "gjorde", "gjort", "Hvad gør du i weekenden?", "What are you doing at the weekend?", ["core"], { imperative: "gør", usage: "'gøre' is doing an action; 'lave' is making a thing. Both translate as 'do' in English." }),
  irr("finde", "find", "finder", "fandt", "fundet", "Jeg kan ikke finde mine nøgler.", "I can't find my keys.", ["core"], { usage: "'finde ud af' = find out / work out." }),
  irr("stå", "stand", "står", "stod", "stået", "Der står en cykel i gården.", "There's a bike standing in the yard.", ["core", "body"], { usage: "Danish says where a thing stands, sits or lies rather than that it just 'is'." }),
  irr("ligge", "lie / be situated", "ligger", "lå", "ligget", "Byen ligger tæt på havet.", "The town lies close to the sea.", ["core", "home"], { usage: "For a thing lying flat, and for where places are: butikken ligger på hjørnet." }),
  irr("sidde", "sit", "sidder", "sad", "siddet", "Vi sad og talte i to timer.", "We sat talking for two hours.", ["core", "body"], { usage: "'sidde og' + verb is how Danish says 'be busy doing' — sidder og læser." }),
  irr("vide", "know (a fact)", "ved", "vidste", "vidst", "Jeg ved det ikke.", "I don't know.", ["core", "thinking"], { imperative: "vid", usage: "Facts only. Knowing a person or place is 'kende'." }),
  irr("kende", "know (a person or place)", "kender", "kendte", "kendt", "Kender du hende?", "Do you know her?", ["core", "social"], { usage: "People and places. For facts use 'vide'." }),
  r1("tro", "believe / think", "Jeg tror, det regner i morgen.", "I think it will rain tomorrow.", ["core", "thinking"], { usage: "An opinion you are not sure of. Note the comma before the second clause — Danish keeps it." }),
  irr("synes", "think / find", "synes", "syntes", "syntes", "Jeg synes, filmen var god.", "I thought the film was good.", ["core", "thinking"], { usage: "Your personal impression of something you have experienced. Ends in -s in every tense." }),
  r2("tænke", "think", "Jeg tænker på min familie.", "I'm thinking about my family.", ["core", "thinking"], { usage: "The mental activity itself: 'tænke på' = think about. For an opinion use 'synes' or 'mene'." }),
  r2("mene", "mean / be of the opinion", "Hvad mener du om forslaget?", "What do you think of the proposal?", ["core", "thinking", "communication"], { usage: "A considered opinion, and 'mean' in the sense of intending something." }),

  // --- 26-60: everyday actions -------------------------------------------
  irr("ske", "happen", "sker", "skete", "sket", "Der skete en ulykke på vejen.", "An accident happened on the road.", ["core", "change"], { aux: "er", usage: "Impersonal: 'der sker noget' = something is happening." }),
  irr("sætte", "put / set", "sætter", "satte", "sat", "Sæt tallerkenen på bordet.", "Put the plate on the table.", ["everyday", "home"], { imperative: "sæt", usage: "'sætte sig' = sit down (the action); 'sidde' is already sitting." }),
  irr("holde", "hold / keep / stop", "holder", "holdt", "holdt", "Bussen holder ved stationen.", "The bus stops at the station.", ["everyday"], { usage: "'holde pause' = take a break; 'holde af' = be fond of; a vehicle 'holder' when it is stationary." }),
  irr("lade", "let / leave", "lader", "lod", "ladet", "Lad mig hjælpe dig.", "Let me help you.", ["core"], { imperative: "lad", usage: "'lad os' = let's; 'lade være med at' = refrain from." }),
  r2("bruge", "use / spend", "Jeg bruger to timer på lektier.", "I spend two hours on homework.", ["everyday"], { usage: "Both using a thing and spending time or money: bruge penge på." }),
  r1("arbejde", "work", "Jeg arbejder på et kontor i Aarhus.", "I work in an office in Aarhus.", ["work"], { usage: "'arbejde med' = work with/in a field; 'arbejde på' = work on a task." }),
  irr("spørge", "ask", "spørger", "spurgte", "spurgt", "Må jeg spørge om noget?", "May I ask something?", ["communication"], { imperative: "spørg", usage: "'spørge om' = ask about; you ask a person 'spørge nogen'." }),
  r1("svare", "answer", "Hun svarede ikke på min mail.", "She didn't answer my email.", ["communication"], { usage: "'svare på' something, 'svare nogen' someone." }),
  r1("snakke", "chat / talk", "Vi snakkede om ferien.", "We chatted about the holiday.", ["communication", "social"], { usage: "Everyday and informal. 'tale' is the neutral word." }),
  r2("tale", "speak", "Taler du dansk?", "Do you speak Danish?", ["communication"], { usage: "'tale med' = speak with; 'tale om' = talk about." }),
  r2("læse", "read / study", "Jeg læser avisen hver morgen.", "I read the newspaper every morning.", ["school", "everyday"], { usage: "Also 'study at university': hun læser medicin." }),
  irr("skrive", "write", "skriver", "skrev", "skrevet", "Jeg skriver et brev til kommunen.", "I'm writing a letter to the municipality.", ["communication", "school"], { usage: "'skrive til' someone, 'skrive under' = sign." }),
  r2("høre", "hear", "Jeg kan ikke høre dig.", "I can't hear you.", ["everyday", "communication"], { usage: "'høre efter' = listen carefully; 'høre til' = belong to." }),
  r2("spise", "eat", "Vi spiser aftensmad klokken seks.", "We eat dinner at six.", ["everyday"], { usage: "Meals take no article: spise morgenmad, spise frokost." }),
  irr("drikke", "drink", "drikker", "drak", "drukket", "Han drikker kaffe uden sukker.", "He drinks coffee without sugar.", ["everyday"], {}),
  irr("sove", "sleep", "sover", "sov", "sovet", "Børnene sover allerede.", "The children are already asleep.", ["everyday", "body"], { usage: "'sove over sig' = oversleep." }),
  r1("bo", "live / reside", "Vi bor i en lejlighed i Odense.", "We live in a flat in Odense.", ["home"], { usage: "Where you live. Being alive is 'leve'." }),
  irr("hedde", "be called", "hedder", "hed", "heddet", "Jeg hedder Sara.", "My name is Sara.", ["core", "social"], { usage: "Danish has no 'my name is' — you 'are called'." }),
  irr("hjælpe", "help", "hjælper", "hjalp", "hjulpet", "Kan du hjælpe mig med formularen?", "Can you help me with the form?", ["social"], { imperative: "hjælp", usage: "'hjælpe nogen med noget' — the thing takes 'med'." }),
  r2("købe", "buy", "Jeg købte en cykel i går.", "I bought a bike yesterday.", ["money", "everyday"], { usage: "'købe ind' = do the shopping." }),
  r2("betale", "pay", "Vi betaler husleje den første i måneden.", "We pay rent on the first of the month.", ["money"], { usage: "'betale for' something, 'betale nogen' someone." }),
  r2("sende", "send", "Jeg sender dig et billede.", "I'll send you a picture.", ["communication"], { usage: "'sende noget til nogen'." }),
  r1("vente", "wait / expect", "Jeg venter på bussen.", "I'm waiting for the bus.", ["everyday"], { usage: "'vente på' = wait for. Without 'på' it means expect: jeg venter et barn." }),
  r2("møde", "meet", "Vi mødte hinanden på sprogskolen.", "We met each other at language school.", ["social"], { usage: "'møde op' = turn up; 'mødes' = meet each other." }),
  r2("begynde", "begin", "Kurset begynder i august.", "The course begins in August.", ["change", "school"], { usage: "'begynde på' something, 'begynde at' + verb." }),
  r1("slutte", "end / finish", "Filmen slutter klokken ti.", "The film ends at ten.", ["change"], { usage: "Intransitive — the thing itself ends. To finish something is 'afslutte'." }),
  r2("lære", "learn / teach", "Jeg lærer nye ord hver dag.", "I learn new words every day.", ["school"], { usage: "Both directions: 'lære dansk' = learn Danish, 'lære nogen at svømme' = teach someone to swim." }),
  r1("prøve", "try", "Prøv at sige det igen.", "Try saying it again.", ["everyday"], { usage: "'prøve at' + infinitive; 'prøve noget' = try something on or out." }),
  r1("kigge", "look", "Hun kiggede ud ad vinduet.", "She looked out of the window.", ["everyday", "body"], { usage: "'kigge på' = look at; 'kigge forbi' = drop by." }),

  // --- 61-120: home, family, daily routine --------------------------------
  irr("stå op", "get up", "står op", "stod op", "stået op", "Jeg står op klokken seks.", "I get up at six.", ["everyday", "body"], { aux: "er", imperative: "stå op", usage: "Two words, always. 'op' never moves: står altid op tidligt." }),
  r1("vågne", "wake up", "Jeg vågnede midt om natten.", "I woke up in the middle of the night.", ["everyday", "body"], { aux: "er", usage: "Waking up happens to you; 'vække' is waking someone else." }),
  r1("vække", "wake someone", "Kan du vække mig klokken syv?", "Can you wake me at seven?", ["everyday"], {}),
  r1("vaske", "wash", "Jeg vasker tøj om lørdagen.", "I do laundry on Saturdays.", ["home", "everyday"], { usage: "'vaske op' = do the dishes; 'vaske sig' = wash yourself." }),
  r1("bade", "bathe / shower", "Han bader hver morgen.", "He showers every morning.", ["everyday", "body"], {}),
  r2("rede", "tidy / make (a bed)", "Jeg reder seng, før jeg går.", "I make the bed before I leave.", ["home"], { usage: "Mostly in 'rede seng' and 'rede hår'." }),
  r1("lave", "make / do", "Hvad laver du?", "What are you doing?", ["everyday", "home"], { usage: "The most useful verb in the language for small talk. 'lave mad' = cook." }),
  r2("koge", "boil / cook", "Vandet koger allerede.", "The water is boiling already.", ["home", "everyday"], {}),
  r2("stege", "fry / roast", "Jeg steger fisk til aftensmad.", "I'm frying fish for dinner.", ["home"], { usage: "Also irregular in speech as stegte/stegt — both forms are met." }),
  r2("bage", "bake", "Vi bager boller om søndagen.", "We bake buns on Sundays.", ["home"], {}),
  r1("rydde", "clear / tidy", "Ryd op på dit værelse.", "Tidy up your room.", ["home"], { usage: "Almost always 'rydde op'." }),
  irr("gøre rent", "clean", "gør rent", "gjorde rent", "gjort rent", "Vi gør rent hver fredag.", "We clean every Friday.", ["home"], { usage: "Two words, always. The noun is 'rengøring'." }),
  r1("flytte", "move (house)", "Vi flytter til Aarhus til sommer.", "We're moving to Aarhus this summer.", ["home", "change"], { usage: "'flytte ind' = move in; 'flytte sig' = move out of the way." }),
  r1("leje", "rent", "Vi lejer en lejlighed på tredje sal.", "We rent a flat on the third floor.", ["home", "money"], { usage: "'leje' = rent from someone; 'udleje' = rent out." }),
  r1("male", "paint", "Vi malede stuen hvid.", "We painted the living room white.", ["home"], {}),
  r1("reparere", "repair", "Han reparerer sin cykel selv.", "He repairs his bike himself.", ["home", "work"], {}),
  r1("bygge", "build", "De bygger et nyt bibliotek.", "They're building a new library.", ["work", "change"], {}),
  r1("plante", "plant", "Jeg plantede blomster i haven.", "I planted flowers in the garden.", ["home"], {}),
  r1("passe", "look after / fit / suit", "Kan du passe børnene i aften?", "Can you look after the children tonight?", ["social", "home"], { usage: "Three senses: mind, fit (bukserne passer), and suit (det passer mig fint). 'Det passer' also means 'that's true'." }),
  r1("hente", "fetch / pick up", "Jeg henter børnene klokken fire.", "I pick the children up at four.", ["everyday", "movement"], {}),
  r1("aflevere", "hand in / drop off", "Jeg afleverer opgaven på fredag.", "I'll hand the assignment in on Friday.", ["school", "admin"], {}),
  r2("køre", "drive / ride", "Jeg kører i bil til arbejde.", "I drive to work.", ["movement"], { usage: "Any wheeled travel, including as a passenger: jeg kører med bus." }),
  r2("rejse", "travel", "Vi rejser til Norge i juli.", "We're travelling to Norway in July.", ["movement"], { aux: "er", usage: "'rejse sig' = stand up, and takes 'har'." }),
  irr("løbe", "run", "løber", "løb", "løbet", "Hun løber en tur hver morgen.", "She goes for a run every morning.", ["body", "movement"], { aux: "er", usage: "'løbe tør for' = run out of." }),
  r1("cykle", "cycle", "Jeg cykler til stationen.", "I cycle to the station.", ["movement", "body"], { usage: "Regular group 1 in every form — listed apart only because it is so common." }),
  irr("flyve", "fly", "flyver", "fløj", "fløjet", "Vi flyver til København i morgen.", "We're flying to Copenhagen tomorrow.", ["movement"], { aux: "er" }),
  irr("gå ud", "go out", "går ud", "gik ud", "gået ud", "Vi går ud og spiser i aften.", "We're going out to eat tonight.", ["social", "movement"], { aux: "er", usage: "Socially: going out for the evening." }),
  irr("gå ind", "go in / enter", "går ind", "gik ind", "gået ind", "Han gik ind i butikken.", "He went into the shop.", ["movement"], { aux: "er" }),
  irr("komme hjem", "get home", "kommer hjem", "kom hjem", "kommet hjem", "Jeg kommer hjem klokken fem.", "I get home at five.", ["movement", "everyday"], { aux: "er" }),
  irr("ankomme", "arrive", "ankommer", "ankom", "ankommet", "Toget ankommer klokken 14.30.", "The train arrives at 14:30.", ["movement", "admin"], { aux: "er", usage: "Formal — timetables and notices. Everyday Danish says 'komme'." }),
  irr("forlade", "leave (a place)", "forlader", "forlod", "forladt", "Hun forlod mødet tidligt.", "She left the meeting early.", ["movement"], {}),
  r2("besøge", "visit", "Vi besøger min mor hver søndag.", "We visit my mother every Sunday.", ["social"], {}),
  r1("invitere", "invite", "De inviterede os til middag.", "They invited us to dinner.", ["social"], { usage: "'invitere nogen til' something." }),
  r1("takke", "thank", "Jeg vil gerne takke jer for hjælpen.", "I'd like to thank you for the help.", ["social", "communication"], { usage: "'takke for' something. Regular group 1 in past: takkede." }),
  r2("hilse", "greet / say hello", "Hils din familie fra mig.", "Say hello to your family from me.", ["social", "communication"], { usage: "'hilse på' = say hello to; 'hils fra mig' = give my regards." }),
  r1("smile", "smile", "Hun smilede til mig.", "She smiled at me.", ["feeling", "social"], { usage: "'smile til' someone." }),
  irr("le", "laugh", "ler", "lo", "leet", "Vi lo hele aftenen.", "We laughed all evening.", ["feeling", "social"], { usage: "'grine' is the everyday word; 'le' is slightly more formal." }),
  irr("græde", "cry", "græder", "græd", "grædt", "Barnet græd hele natten.", "The child cried all night.", ["feeling"], { usage: "Strong in speech too: græder, græd, grædt." }),
  r1("elske", "love", "Jeg elsker at læse danske bøger.", "I love reading Danish books.", ["feeling"], { usage: "Group 1 in past: elskede. Stronger than English 'love' about things." }),
  r1("hade", "hate", "Jeg hader at stå tidligt op.", "I hate getting up early.", ["feeling"], { usage: "Group 1 in past: hadede." }),
  r1("savne", "miss", "Jeg savner min familie.", "I miss my family.", ["feeling"], {}),
  r1("håbe", "hope", "Jeg håber, du får det bedre.", "I hope you get better.", ["feeling", "thinking"], { usage: "'håbe på' something; 'håbe at' + clause." }),
  r1("ønske", "wish", "Jeg ønsker mig en ny cykel.", "I'd like a new bike.", ["feeling"], { usage: "'ønske sig' = wish for yourself — the reflexive is what makes it a wish rather than a demand." }),
  irr("glæde sig", "look forward", "glæder sig", "glædede sig", "glædet sig", "Jeg glæder mig til ferien.", "I'm looking forward to the holiday.", ["feeling"], { usage: "Always reflexive, always with 'til'. This is how Danish says 'look forward to'." }),
  irr("ærgre sig", "be annoyed", "ærgrer sig", "ærgrede sig", "ærgret sig", "Jeg ærgrer mig over, at jeg glemte det.", "I'm annoyed that I forgot it.", ["feeling"], { usage: "Reflexive, with 'over'." }),
  r2("undskylde", "apologise / excuse", "Undskyld, jeg kommer for sent.", "Sorry, I'm late.", ["social", "communication"], { usage: "'Undskyld' on its own is the everyday 'sorry' and 'excuse me'." }),
  irr("tilgive", "forgive", "tilgiver", "tilgav", "tilgivet", "Hun tilgav ham aldrig.", "She never forgave him.", ["feeling", "social"], { usage: "'tilgive nogen noget'." }),
  r1("huske", "remember", "Kan du huske hendes navn?", "Can you remember her name?", ["thinking"], { usage: "'huske på' = keep in mind." }),
  irr("glemme", "forget", "glemmer", "glemte", "glemt", "Jeg glemte min telefon derhjemme.", "I forgot my phone at home.", ["thinking"], {}),
  irr("forstå", "understand", "forstår", "forstod", "forstået", "Jeg forstår ikke spørgsmålet.", "I don't understand the question.", ["thinking", "communication"], {}),
  r1("forklare", "explain", "Kan du forklare reglen igen?", "Can you explain the rule again?", ["communication", "school"], { usage: "'forklare noget for nogen'." }),
  irr("gentage", "repeat", "gentager", "gentog", "gentaget", "Vil du gentage det, tak?", "Would you repeat that, please?", ["communication", "school"], { usage: "'Vil du gentage det?' is the polite way to ask for a repeat." }),
  irr("øve sig", "practise", "øver sig", "øvede sig", "øvet sig", "Jeg øver mig på udtalen hver dag.", "I practise pronunciation every day.", ["school"], { usage: "Reflexive, with 'på'." }),
  r1("gætte", "guess", "Gæt, hvem jeg mødte i dag.", "Guess who I met today.", ["thinking"], {}),
  r2("vise", "show", "Kan du vise mig vejen?", "Can you show me the way?", ["communication"], { usage: "'vise sig' = turn out / appear." }),
  irr("betyde", "mean", "betyder", "betød", "betydet", "Hvad betyder det ord?", "What does that word mean?", ["communication", "thinking"], { usage: "About meaning, never about intention — for that use 'mene'." }),
  r1("stave", "spell", "Hvordan staver man til det?", "How do you spell that?", ["school", "communication"], { usage: "'stave til' something." }),
  irr("oversætte", "translate", "oversætter", "oversatte", "oversat", "Jeg oversætter teksten til engelsk.", "I'm translating the text into English.", ["school", "communication"], { usage: "'oversætte fra ... til ...'." }),
  r2("undervise", "teach", "Hun underviser i dansk.", "She teaches Danish.", ["school", "work"], { usage: "'undervise i' a subject." }),

  // --- work, money and the Danish of officialdom --------------------------
  r2("søge", "apply / search", "Jeg søger job som pædagogmedhjælper.", "I'm applying for a job as a childcare assistant.", ["work", "admin"], { usage: "'søge om' = apply for (a permit); 'søge efter' = search for." }),
  r2("ansøge", "apply (formally)", "Hun ansøgte om permanent opholdstilladelse.", "She applied for permanent residence.", ["admin"], { usage: "Formal register — letters and forms. 'ansøge om' something." }),
  irr("ansætte", "employ / hire", "ansætter", "ansatte", "ansat", "Firmaet ansatte tre nye medarbejdere.", "The company hired three new employees.", ["work"], { usage: "'blive ansat' = be taken on. The noun 'en ansat' is an employee." }),
  r1("fyre", "fire / sack", "Han blev fyret sidste måned.", "He was fired last month.", ["work"], {}),
  r2("tjene", "earn", "Jeg tjener 130 kroner i timen.", "I earn 130 kroner an hour.", ["money", "work"], { usage: "'tjene penge' = earn money; 'tjene til' = serve as." }),
  r1("spare", "save (money)", "Vi sparer op til en ferie.", "We're saving up for a holiday.", ["money"], { usage: "'spare op til' = save up for; 'spare på' = go easy on." }),
  r1("koste", "cost", "Hvor meget koster billetten?", "How much does the ticket cost?", ["money"], {}),
  r2("låne", "borrow / lend", "Må jeg låne din telefon?", "May I borrow your phone?", ["money", "social"], { usage: "Both directions. 'låne af' = borrow from; 'låne til' = lend to." }),
  r2("skylde", "owe", "Jeg skylder dig hundrede kroner.", "I owe you a hundred kroner.", ["money"], {}),
  irr("bestille", "order / book", "bestiller", "bestilte", "bestilt", "Jeg har bestilt tid hos lægen.", "I've booked an appointment with the doctor.", ["admin", "everyday"], { usage: "'bestille tid' is the fixed way to make any appointment." }),
  r2("aflyse", "cancel", "Mødet blev aflyst i sidste øjeblik.", "The meeting was cancelled at the last minute.", ["admin"], { usage: "An event is 'aflyst'; a person cancels their own attendance with 'melde afbud'." }),
  r2("udfylde", "fill in (a form)", "Udfyld blanketten med blokbogstaver.", "Fill in the form in block letters.", ["admin"], {}),
  irr("underskrive", "sign", "underskriver", "underskrev", "underskrevet", "Du skal underskrive kontrakten.", "You need to sign the contract.", ["admin"], { usage: "Everyday Danish says 'skrive under'." }),
  r2("melde", "report / register", "Du skal melde flytning til kommunen.", "You must report your change of address to the municipality.", ["admin"], { usage: "'melde sig til' = sign up for; 'melde afbud' = cancel your attendance." }),
  irr("tilmelde sig", "sign up", "tilmelder sig", "tilmeldte sig", "tilmeldt sig", "Jeg har tilmeldt mig et danskkursus.", "I've signed up for a Danish course.", ["admin", "school"], { usage: "Reflexive, then 'til' for what you signed up to." }),
  r1("bevilge", "grant / award", "Kommunen bevilgede støtte til kurset.", "The municipality granted support for the course.", ["admin", "money"], { usage: "The word that appears in letters from the kommune granting something." }),
  r2("godkende", "approve", "Kommunen godkendte ansøgningen.", "The municipality approved the application.", ["admin"], {}),
  r2("afvise", "reject / turn away", "Ansøgningen blev afvist.", "The application was rejected.", ["admin"], { usage: "'afvise en ansøgning' = reject an application." }),
  r1("kræve", "demand / require", "Jobbet kræver, at du taler dansk.", "The job requires you to speak Danish.", ["work", "admin"], {}),
  irr("tilbyde", "offer", "tilbyder", "tilbød", "tilbudt", "De tilbød mig en fast stilling.", "They offered me a permanent position.", ["work"], { usage: "'tilbyde nogen noget'. The noun 'et tilbud' is also a special offer in a shop." }),
  irr("modtage", "receive", "modtager", "modtog", "modtaget", "Jeg modtog brevet i går.", "I received the letter yesterday.", ["admin"], { usage: "Formal. Everyday Danish says 'få'." }),
  r2("indsende", "submit", "Indsend ansøgningen inden den 1. maj.", "Submit the application before 1 May.", ["admin"], {}),
  r1("kontakte", "contact", "Kontakt din sagsbehandler i god tid.", "Contact your caseworker in good time.", ["admin", "communication"], {}),
  irr("henvende sig", "get in touch / approach", "henvender sig", "henvendte sig", "henvendt sig", "Henvend dig i receptionen.", "Report to reception.", ["admin"], { usage: "Reflexive: henvender sig, henvendte sig, henvendt sig — the fixed phrase on Danish signs." }),
  r2("oplyse", "state / inform", "Oplys dit CPR-nummer.", "State your CPR number.", ["admin"], {}),
  r1("bekræfte", "confirm", "Kan du bekræfte tidspunktet?", "Can you confirm the time?", ["admin", "communication"], { usage: "Used of a booking, an appointment, or that something is true." }),
  r1("ændre", "change / alter", "Vi ændrede planen i sidste øjeblik.", "We changed the plan at the last minute.", ["change", "admin"], { usage: "'ændre sig' = change by itself." }),
  irr("vælge", "choose", "vælger", "valgte", "valgt", "Du skal vælge mellem to kurser.", "You have to choose between two courses.", ["thinking"], { usage: "'vælge mellem' = choose between; 'vælge at' + verb." }),
  r1("beslutte", "decide", "Vi besluttede at flytte.", "We decided to move.", ["thinking"], { usage: "'beslutte sig for' = make up your mind about." }),
  irr("planlægge", "plan", "planlægger", "planlagde", "planlagt", "Vi planlægger ferien i januar.", "We plan the holiday in January.", ["thinking", "work"], { usage: "A compound of 'lægge', and it inherits its forms." }),
  r1("arrangere", "arrange", "Hun arrangerede en fest til hans fødselsdag.", "She arranged a party for his birthday.", ["social", "work"], {}),
  irr("deltage", "take part", "deltager", "deltog", "deltaget", "Jeg deltager i mødet på torsdag.", "I'm taking part in the meeting on Thursday.", ["work", "social"], { usage: "'deltage i' something." }),
  irr("undgå", "avoid", "undgår", "undgik", "undgået", "Prøv at undgå myldretiden.", "Try to avoid the rush hour.", ["thinking"], { usage: "'undgå at' + verb = avoid doing." }),
  r1("nå", "reach / make it in time", "Jeg nåede toget med et minut til overs.", "I made the train with a minute to spare.", ["movement", "time"], { usage: "'nå at' + verb = manage to do in time." }),
  r1("mangle", "lack / be missing", "Der mangler en underskrift.", "A signature is missing.", ["admin"], {}),
  irr("gælde", "apply / be valid", "gælder", "gjaldt", "gældt", "Billetten gælder i to timer.", "The ticket is valid for two hours.", ["admin"], { usage: "'det gælder om at' = the thing is to." }),
  irr("bestemme", "decide / determine", "bestemmer", "bestemte", "bestemt", "Det er dig, der bestemmer.", "You're the one who decides.", ["thinking"], { usage: "'bestemme sig for' = make up your mind." }),
  irr("foreslå", "suggest", "foreslår", "foreslog", "foreslået", "Jeg foreslår, at vi mødes klokken to.", "I suggest we meet at two.", ["communication"], { usage: "'foreslå, at' + clause is the polite way to propose something." }),
  r1("diskutere", "discuss", "Vi diskuterede sagen i en time.", "We discussed the matter for an hour.", ["communication"], {}),
  r2("nævne", "mention", "Han nævnte det ikke med et ord.", "He didn't mention it at all.", ["communication"], {}),
  irr("fortælle", "tell", "fortæller", "fortalte", "fortalt", "Fortæl mig om din weekend.", "Tell me about your weekend.", ["communication"], { usage: "'fortælle om' something, 'fortælle nogen noget'." }),
  irr("beskrive", "describe", "beskriver", "beskrev", "beskrevet", "Beskriv billedet med dine egne ord.", "Describe the picture in your own words.", ["communication", "school"], { usage: "The instruction on almost every Modul 2 speaking task." }),
  r2("henvise", "refer", "Lægen henviste mig til en specialist.", "The doctor referred me to a specialist.", ["admin", "body"], { usage: "'henvise til' = refer to." }),
  r1("klage", "complain", "Du kan klage over afgørelsen.", "You can appeal against the decision.", ["admin", "communication"], { usage: "'klage over' something; in officialdom it means to appeal." }),
  r1("rette", "correct", "Læreren rettede mine fejl.", "The teacher corrected my mistakes.", ["school"], { usage: "'rette sig efter' = comply with." }),
  irr("gemme", "save / hide", "gemmer", "gemte", "gemt", "Gem dokumentet, før du lukker.", "Save the document before you close it.", ["everyday"], { usage: "Both 'store' and 'hide' — context decides." }),
  irr("finde ud af", "find out", "finder ud af", "fandt ud af", "fundet ud af", "Jeg fandt ud af, hvor kontoret ligger.", "I found out where the office is.", ["thinking"], { usage: "The everyday way to say 'find out' or 'work out'." }),
  r2("undersøge", "investigate / look into", "Lægen undersøgte mit knæ.", "The doctor examined my knee.", ["body", "work"], { usage: "Also what a doctor does to you: lægen undersøgte mig." }),
  r1("kontrollere", "check", "Kontroller, at alle felter er udfyldt.", "Check that all fields are filled in.", ["admin"], {}),
  r1("tjekke", "check", "Jeg tjekker lige min kalender.", "Let me just check my calendar.", ["everyday", "admin"], { usage: "The everyday word; 'kontrollere' is the formal one." }),

  // --- body, health and the doctor's surgery ------------------------------
  irr("gøre ondt", "hurt", "gør ondt", "gjorde ondt", "gjort ondt", "Min ryg gør ondt om morgenen.", "My back hurts in the morning.", ["body"], { usage: "The Danish for 'it hurts'. The body part is the subject: min hals gør ondt." }),
  r2("føle", "feel", "Jeg føler mig bedre i dag.", "I feel better today.", ["body", "feeling"], { usage: "'føle sig' + adjective is how you say how you are." }),
  irr("have det", "feel / be doing", "har det", "havde det", "haft det", "Hvordan har du det?", "How are you?", ["body", "social"], { usage: "The standard greeting. 'Jeg har det godt' = I'm fine." }),
  irr("blive syg", "fall ill", "bliver syg", "blev syg", "blevet syg", "Han blev syg i weekenden.", "He fell ill at the weekend.", ["body", "change"], { aux: "er" }),
  irr("sove ind", "fall asleep", "sover ind", "sov ind", "sovet ind", "Jeg sov ind foran fjernsynet.", "I fell asleep in front of the TV.", ["body"], { aux: "er" }),
  r1("hvile", "rest", "Læreren sagde, jeg skulle hvile mig.", "The teacher said I should rest.", ["body"], { usage: "Often reflexive: hvile sig." }),
  r1("træne", "train / exercise", "Jeg træner tre gange om ugen.", "I exercise three times a week.", ["body"], {}),
  r1("svømme", "swim", "Vi svømmer i havet om sommeren.", "We swim in the sea in the summer.", ["body", "movement"], { usage: "'svømme en tur' = go for a swim." }),
  r1("danse", "dance", "De dansede hele natten.", "They danced all night.", ["body", "social"], {}),
  irr("springe", "jump", "springer", "sprang", "sprunget", "Børnene sprang i vandet.", "The children jumped into the water.", ["body", "movement"], { aux: "er" }),
  irr("falde", "fall", "falder", "faldt", "faldet", "Hun faldt på isen.", "She fell on the ice.", ["body", "movement"], { aux: "er", usage: "'falde i søvn' = fall asleep." }),
  irr("bære", "carry", "bærer", "bar", "båret", "Kan du bære den her taske?", "Can you carry this bag?", ["body"], {}),
  irr("trække", "pull", "trækker", "trak", "trukket", "Træk i håndtaget.", "Pull the handle.", ["body"], { usage: "'trække vejret' = breathe; 'trække sig' = withdraw." }),
  r1("skubbe", "push", "Skub døren op.", "Push the door open.", ["body"], {}),
  irr("holde fast", "hold on", "holder fast", "holdt fast", "holdt fast", "Hold fast i gelænderet.", "Hold on to the railing.", ["body"], {}),
  irr("slå", "hit / strike", "slår", "slog", "slået", "Jeg slog mit knæ mod bordet.", "I hit my knee on the table.", ["body"], { usage: "'slå op' = look up; 'slå fra' = switch off." }),
  irr("skære", "cut", "skærer", "skar", "skåret", "Skær brødet i tynde skiver.", "Cut the bread into thin slices.", ["home", "body"], {}),
  r1("åbne", "open", "Butikken åbner klokken ni.", "The shop opens at nine.", ["everyday"], {}),
  r1("lukke", "close", "De lukker klokken atten.", "They close at six p.m.", ["everyday"], { usage: "'lukke op' = open up; 'lukke ned' = shut down." }),
  r2("tænde", "switch on / light", "Tænd lyset, det er mørkt.", "Turn the light on, it's dark.", ["home"], { usage: "Also of a candle or a fire." }),
  r1("slukke", "switch off", "Husk at slukke ovnen.", "Remember to turn the oven off.", ["home"], { usage: "The opposite of 'tænde', for lights, ovens and screens." }),
  irr("tage på", "put on (clothes) / gain weight", "tager på", "tog på", "taget på", "Tag en varm jakke på.", "Put a warm jacket on.", ["everyday", "body"], { usage: "The 'på' can move to the end: tag jakken på." }),
  irr("tage af", "take off", "tager af", "tog af", "taget af", "Tag skoene af i gangen.", "Take your shoes off in the hallway.", ["everyday"], {}),
  irr("klæde sig på", "get dressed", "klæder sig på", "klædte sig på", "klædt sig på", "Børnene klæder sig på selv.", "The children dress themselves.", ["everyday", "body"], { usage: "Reflexive. 'klæde sig af' = get undressed." }),
  r1("skifte", "change (clothes, trains)", "Du skal skifte tog i Odense.", "You have to change trains in Odense.", ["movement", "everyday"], { usage: "'skifte tog' = change trains; 'skifte tøj' = change clothes." }),

  // --- food, shopping and the week ----------------------------------------
  r2("smage", "taste", "Suppen smager af hvidløg.", "The soup tastes of garlic.", ["everyday"], { usage: "'smage af' = taste of; 'smage på' = have a taste of." }),
  r1("lugte", "smell", "Der lugter af nybagt brød.", "It smells of freshly baked bread.", ["body"], { usage: "'lugte af' something." }),
  r1("servere", "serve", "De serverer morgenmad fra klokken syv.", "They serve breakfast from seven.", ["work", "home"], {}),
  irr("dække bord", "set the table", "dækker bord", "dækkede bord", "dækket bord", "Kan du dække bord?", "Can you set the table?", ["home"], { usage: "Fixed expression — no article on 'bord'." }),
  r2("hælde", "pour", "Hæld mælken i skålen.", "Pour the milk into the bowl.", ["home"], { usage: "'hælde noget i' or 'op i' something." }),
  r1("blande", "mix", "Bland alle ingredienserne godt.", "Mix all the ingredients well.", ["home"], { usage: "'blande sig i' = interfere in." }),
  r1("skrælle", "peel", "Jeg skræller kartoflerne.", "I'm peeling the potatoes.", ["home"], {}),
  r1("handle", "shop / act", "Jeg handler ind om fredagen.", "I do the shopping on Fridays.", ["money", "everyday"], { usage: "'handle ind' = do the shopping; 'handle om' = be about." }),
  irr("sælge", "sell", "sælger", "solgte", "solgt", "De sælger cykler brugt.", "They sell bikes second-hand.", ["money"], { usage: "'sælge noget til nogen'." }),
  r1("bytte", "swap / exchange", "Kan jeg bytte den her trøje?", "Can I exchange this jumper?", ["money"], {}),
  r1("miste", "lose (for good)", "Han mistede sit job i marts.", "He lost his job in March.", ["change"], { usage: "'tabe' is dropping something; 'miste' is losing it for good." }),
  irr("vinde", "win", "vinder", "vandt", "vundet", "Vores hold vandt kampen.", "Our team won the match.", ["social"], { usage: "'vinde over nogen' = beat someone." }),
  r2("tabe", "lose", "Jeg har tabt mit kort.", "I've lost my card.", ["everyday"], { usage: "'tabe sig' = lose weight; 'miste' is losing something for good." }),
  irr("finde på", "come up with", "finder på", "fandt på", "fundet på", "Han fandt på en god undskyldning.", "He came up with a good excuse.", ["thinking"], {}),

  // --- time, weather and the calendar -------------------------------------
  r1("vare", "last", "Kurset varer tre måneder.", "The course lasts three months.", ["time"], { usage: "About duration only." }),
  r1("starte", "start", "Filmen starter om ti minutter.", "The film starts in ten minutes.", ["change", "time"], {}),
  irr("fortsætte", "continue", "fortsætter", "fortsatte", "fortsat", "Vi fortsætter i morgen.", "We'll continue tomorrow.", ["change"], { usage: "'fortsætte med at' + verb." }),
  irr("blive ved", "keep on", "bliver ved", "blev ved", "blevet ved", "Hun blev ved med at tale.", "She kept on talking.", ["change"], { aux: "er", usage: "'blive ved med at' + verb." }),
  r1("regne", "rain / count on", "Det regner igen i dag.", "It's raining again today.", ["everyday"], { usage: "'regne med' = count on / expect." }),
  irr("sne", "snow", "sner", "sneede", "sneet", "Det sneede hele natten.", "It snowed all night.", ["everyday"], {}),
  r2("blæse", "blow / be windy", "Det blæser kraftigt fra vest.", "It's blowing hard from the west.", ["everyday"], {}),
  irr("fryse", "freeze / be cold", "fryser", "frøs", "frosset", "Jeg fryser om hænderne.", "My hands are cold.", ["body"], { usage: "Danish says 'jeg fryser', never 'jeg er kold' — that would mean you are a cold person." }),
  r1("skinne", "shine", "Solen skinner i dag.", "The sun is shining today.", ["everyday"], {}),
  irr("regne med", "count on / expect", "regner med", "regnede med", "regnet med", "Jeg regner med at komme klokken syv.", "I expect to be there at seven.", ["thinking"], { usage: "'regne med at' + verb, or 'regne med nogen'." }),
  irr("nå frem", "arrive / get there", "når frem", "nåede frem", "nået frem", "Vi nåede frem klokken otte.", "We got there at eight.", ["movement", "time"], { aux: "er", usage: "'nå frem til' a place, or to a conclusion." }),
  irr("skynde sig", "hurry", "skynder sig", "skyndte sig", "skyndt sig", "Skynd dig, bussen kører nu.", "Hurry up, the bus is leaving now.", ["movement"], { usage: "Always reflexive: skynd dig!" }),

  // --- talking, listening and getting on with people ----------------------
  r1("lytte", "listen", "Lyt godt efter, hvad hun siger.", "Listen carefully to what she says.", ["communication"], { usage: "'lytte til' or 'lytte efter'." }),
  r1("ringe", "call / ring", "Jeg ringer til dig i aften.", "I'll call you tonight.", ["communication"], { usage: "'ringe til' someone. 'Det ringer' also means the doorbell is going." }),
  r1("besvare", "answer (formally)", "Vi besvarer alle henvendelser inden for en uge.", "We answer all enquiries within a week.", ["admin", "communication"], {}),
  r2("meddele", "announce / inform", "Skolen meddelte, at kurset var aflyst.", "The school announced the course was cancelled.", ["admin", "communication"], {}),
  r1("erklære", "declare", "Han erklærede sig enig.", "He declared himself in agreement.", ["communication"], { usage: "'erklære sig enig' is the formal way to agree." }),
  irr("mødes", "meet up", "mødes", "mødtes", "mødtes", "Skal vi mødes klokken to?", "Shall we meet at two?", ["social"], { usage: "The -s form makes it mutual: the two sides meet each other." }),
  r2("aftale", "agree / arrange", "Vi aftalte at ses på fredag.", "We arranged to see each other on Friday.", ["social", "admin"], { usage: "'aftale at' + verb. The noun 'en aftale' is both an agreement and an appointment." }),
  irr("enes", "agree / get along", "enes", "enedes", "enedes", "De enes ikke om noget.", "They don't agree about anything.", ["social"], { usage: "'enes om' something. Always mutual." }),
  irr("skændes", "argue / quarrel", "skændes", "skændtes", "skændtes", "Naboerne skændes hver aften.", "The neighbours argue every evening.", ["social", "feeling"], { usage: "Always mutual — one person cannot 'skændes' alone." }),
  irr("hjælpe til", "lend a hand", "hjælper til", "hjalp til", "hjulpet til", "Alle hjalp til med opvasken.", "Everyone lent a hand with the washing up.", ["social"], { usage: "'hjælpe til med' something." }),
  r1("støtte", "support", "Min familie støtter mig meget.", "My family supports me a lot.", ["social", "feeling"], { usage: "Of people and of causes alike." }),
  r1("stole", "trust", "Jeg stoler på min nabo.", "I trust my neighbour.", ["feeling", "social"], { usage: "Always 'stole på'." }),
  r1("love", "promise", "Han lovede at ringe.", "He promised to call.", ["communication"], { usage: "'love nogen noget'; 'love at' + verb." }),
  r1("advare", "warn", "Vejrudsigten advarede mod storm.", "The forecast warned of a storm.", ["communication"], { usage: "'advare mod' something." }),
  r1("true", "threaten", "Han truede med at klage.", "He threatened to complain.", ["feeling"], { usage: "'true med at' + verb." }),
  r2("rose", "praise", "Læreren roste min udtale.", "The teacher praised my pronunciation.", ["social", "school"], { usage: "The forms are regular: roser, roste, rost." }),
  r1("kritisere", "criticise", "Han kritiserede forslaget hårdt.", "He criticised the proposal harshly.", ["communication"], {}),
  r1("anbefale", "recommend", "Jeg kan anbefale den restaurant.", "I can recommend that restaurant.", ["communication"], {}),
  irr("bede", "ask / pray", "beder", "bad", "bedt", "Må jeg bede om regningen?", "May I ask for the bill?", ["communication"], { usage: "'bede om' = ask for — the polite way to order anything in a shop or café." }),
  irr("byde", "offer / bid", "byder", "bød", "budt", "De bød på kaffe og kage.", "They offered coffee and cake.", ["social"], { usage: "'byde velkommen' = welcome; 'byde på' = offer." }),
  irr("nyde", "enjoy", "nyder", "nød", "nydt", "Jeg nyder at gå tur om aftenen.", "I enjoy going for a walk in the evening.", ["feeling"], {}),
  irr("blive enige", "come to an agreement", "bliver enige", "blev enige", "blevet enige", "Vi blev enige om en pris.", "We agreed on a price.", ["social"], { aux: "er", usage: "'blive enige om' something." }),
  r1("præsentere", "introduce / present", "Må jeg præsentere min kollega?", "May I introduce my colleague?", ["social", "work"], { usage: "'præsentere sig' = introduce yourself." }),
  r1("beklage", "regret / be sorry", "Vi beklager forsinkelsen.", "We apologise for the delay.", ["admin", "communication"], { usage: "The formal apology on Danish signs and announcements." }),
  irr("ønske sig", "wish for", "ønsker sig", "ønskede sig", "ønsket sig", "Hun ønsker sig en cykel til jul.", "She wants a bike for Christmas.", ["feeling"], { usage: "The reflexive is what turns a demand into a wish." }),

  // --- thinking, learning and getting things right ------------------------
  irr("undre sig", "wonder", "undrer sig", "undrede sig", "undret sig", "Jeg undrer mig over, hvorfor han ikke kom.", "I wonder why he didn't come.", ["thinking"], { usage: "Reflexive, with 'over'." }),
  r1("overveje", "consider", "Vi overvejer at flytte til Jylland.", "We're considering moving to Jutland.", ["thinking"], { usage: "The forms follow 'veje': overvejer, overvejede, overvejet." }),
  irr("regne ud", "work out", "regner ud", "regnede ud", "regnet ud", "Kan du regne ud, hvor meget det bliver?", "Can you work out how much it comes to?", ["thinking"], {}),
  irr("lægge mærke til", "notice", "lægger mærke til", "lagde mærke til", "lagt mærke til", "Jeg lagde mærke til, at han var stille.", "I noticed he was quiet.", ["thinking"], {}),
  irr("komme i tanke om", "recall suddenly", "kommer i tanke om", "kom i tanke om", "kommet i tanke om", "Jeg kom i tanke om, at jeg havde glemt nøglerne.", "I remembered I'd forgotten my keys.", ["thinking"], { aux: "er" }),
  irr("interessere sig", "be interested", "interesserer sig", "interesserede sig", "interesseret sig", "Jeg interesserer mig for historie.", "I'm interested in history.", ["feeling", "thinking"], { usage: "Reflexive, with 'for'." }),
  irr("koncentrere sig", "concentrate", "koncentrerer sig", "koncentrerede sig", "koncentreret sig", "Det er svært at koncentrere sig i støj.", "It's hard to concentrate in noise.", ["thinking", "school"], { usage: "Reflexive, with 'om'." }),
  irr("gentage sig", "recur", "gentager sig", "gentog sig", "gentaget sig", "Fejlen gentog sig igen.", "The error happened again.", ["change"], { usage: "Of a mistake or an event happening again." }),
  irr("forstå sig på", "know about", "forstår sig på", "forstod sig på", "forstået sig på", "Hun forstår sig på biler.", "She knows about cars.", ["thinking"], {}),
  irr("lære udenad", "learn by heart", "lærer udenad", "lærte udenad", "lært udenad", "Jeg lærte digtet udenad.", "I learned the poem by heart.", ["school"], { usage: "'udenad' is one word and never changes." }),
  r1("notere", "note down", "Notér tiden i din kalender.", "Note the time in your calendar.", ["school", "admin"], {}),
  r1("markere", "mark / highlight", "Markér de ord, du ikke forstår.", "Mark the words you don't understand.", ["school"], {}),
  r1("sammenligne", "compare", "Sammenlign de to tekster.", "Compare the two texts.", ["school", "thinking"], {}),
  irr("forklare sig", "explain oneself", "forklarer sig", "forklarede sig", "forklaret sig", "Han fik lov til at forklare sig.", "He was allowed to explain himself.", ["communication"], {}),
  r1("bemærke", "remark / notice", "Hun bemærkede, at døren stod åben.", "She noticed the door was open.", ["thinking", "communication"], {}),
  r1("betvivle", "doubt", "Ingen betvivler hendes evner.", "Nobody doubts her abilities.", ["thinking"], { usage: "Formal. Everyday Danish says 'jeg tror ikke på det'." }),
  irr("gå i gang", "get started", "går i gang", "gik i gang", "gået i gang", "Vi går i gang klokken ni.", "We get started at nine.", ["change", "work"], { aux: "er", usage: "'gå i gang med' something." }),
  irr("give op", "give up", "giver op", "gav op", "givet op", "Giv ikke op, du er tæt på.", "Don't give up, you're close.", ["feeling"], {}),
  irr("blive færdig", "finish", "bliver færdig", "blev færdig", "blevet færdig", "Jeg blev færdig med opgaven i går.", "I finished the assignment yesterday.", ["change", "school"], { aux: "er", usage: "'blive færdig med' something." }),
  r1("afslutte", "finish (something)", "Vi afsluttede mødet klokken fire.", "We finished the meeting at four.", ["change", "work"], { usage: "Transitive — you finish a thing. 'slutte' is the thing ending by itself." }),
  r2("forberede", "prepare", "Jeg forbereder mig til eksamen.", "I'm preparing for the exam.", ["school"], { usage: "'forberede sig til' something." }),
  irr("gennemgå", "go through / review", "gennemgår", "gennemgik", "gennemgået", "Læreren gennemgik opgaven på tavlen.", "The teacher went through the exercise on the board.", ["school"], { usage: "What a teacher does with an exercise, and a doctor with your results." }),
  irr("rette op på", "put right", "retter op på", "rettede op på", "rettet op på", "Vi må rette op på fejlen.", "We'll have to put the mistake right.", ["change"], {}),
  r1("forbedre", "improve", "Jeg vil gerne forbedre min udtale.", "I'd like to improve my pronunciation.", ["change", "school"], { usage: "'forbedre sig' = get better." }),
  r1("udvikle", "develop", "Sproget udvikler sig hele tiden.", "The language is developing all the time.", ["change"], {}),
  r1("vokse", "grow", "Børnene vokser hurtigt.", "Children grow fast.", ["change", "body"], { aux: "er", usage: "'vokse op' = grow up." }),
  irr("stige", "rise / increase", "stiger", "steg", "steget", "Priserne steg sidste år.", "Prices rose last year.", ["change", "money"], { aux: "er", usage: "'stige på' = board a bus or train; 'stige af' = get off." }),
  irr("falde ned", "fall down", "falder ned", "faldt ned", "faldet ned", "Bogen faldt ned fra hylden.", "The book fell down from the shelf.", ["movement"], { aux: "er", usage: "'falde ned' of a thing; 'falde' of a person." }),
  r1("dale", "drop / decline", "Temperaturen daler i aften.", "The temperature drops tonight.", ["change"], {}),
  irr("ændre sig", "change (by itself)", "ændrer sig", "ændrede sig", "ændret sig", "Vejret ændrede sig hurtigt.", "The weather changed quickly.", ["change"], {}),

  // --- putting things somewhere, and taking them away ---------------------
  irr("lægge", "lay / put down", "lægger", "lagde", "lagt", "Læg papirerne på bordet.", "Put the papers on the table.", ["home", "body"], { usage: "For putting a thing down flat. 'sætte' is standing it up, 'stille' is placing it." }),
  irr("lægge sig", "lie down", "lægger sig", "lagde sig", "lagt sig", "Han lagde sig på sofaen.", "He lay down on the sofa.", ["body"], {}),
  irr("sætte sig", "sit down", "sætter sig", "satte sig", "sat sig", "Sæt dig ned, vi skal snakke.", "Sit down, we need to talk.", ["body"], {}),
  irr("rejse sig", "stand up", "rejser sig", "rejste sig", "rejst sig", "Hun rejste sig og gik.", "She stood up and left.", ["body"], {}),
  r1("stille", "place / put", "Stil cyklen i skuret.", "Put the bike in the shed.", ["home"], { usage: "'stille et spørgsmål' = ask a question." }),
  r1("putte", "pop / put in", "Put pengene i kuverten.", "Put the money in the envelope.", ["everyday"], {}),
  r1("placere", "place / position", "Placer skiltet ved indgangen.", "Position the sign by the entrance.", ["work"], {}),
  r1("fjerne", "remove", "Fjern etiketten, før du vasker den.", "Remove the label before you wash it.", ["home"], {}),
  irr("smide", "throw / chuck", "smider", "smed", "smidt", "Smid det ikke ud, jeg skal bruge det.", "Don't throw it away, I need it.", ["home"], { usage: "'smide ud' = throw away." }),
  r1("kaste", "throw", "Han kastede bolden til hende.", "He threw the ball to her.", ["body"], {}),
  irr("gribe", "catch / grab", "griber", "greb", "grebet", "Hun greb kruset, før det faldt.", "She caught the mug before it fell.", ["body"], { usage: "'gribe ind' = intervene." }),
  r1("samle", "gather / collect", "Jeg samler på frimærker.", "I collect stamps.", ["everyday"], { usage: "'samle op' = pick up; 'samle på' = collect as a hobby." }),
  r2("dele", "share / divide", "Vi deler regningen.", "We're splitting the bill.", ["social", "money"], { usage: "'dele noget med nogen'." }),
  r1("pakke", "pack", "Jeg pakker kufferten i aften.", "I'm packing the suitcase tonight.", ["everyday"], { usage: "'pakke ud' = unpack; 'pakke ind' = wrap." }),
  r2("låse", "lock", "Husk at låse døren.", "Remember to lock the door.", ["home"], { usage: "'låse op' = unlock." }),
  irr("hænge", "hang", "hænger", "hang", "hængt", "Jakken hænger i entreen.", "The jacket is hanging in the hall.", ["home"], { usage: "Hanging by itself is strong (hang); hanging something up is regular: hængte op." }),
  r1("tørre", "dry / wipe", "Tør bordet af, tak.", "Wipe the table, please.", ["home"], { usage: "'tørre af' = wipe; 'tørre op' = mop up." }),
  irr("stryge", "iron / stroke", "stryger", "strøg", "strøget", "Jeg stryger skjorterne om søndagen.", "I iron the shirts on Sundays.", ["home"], {}),
  r1("klippe", "cut (with scissors)", "Hun klippede billedet ud af avisen.", "She cut the picture out of the newspaper.", ["home"], { usage: "'blive klippet' = get a haircut." }),
  r1("børste", "brush", "Børst tænder, før du går i seng.", "Brush your teeth before you go to bed.", ["body", "everyday"], {}),
  r1("feje", "sweep", "Han fejede gården ren.", "He swept the yard clean.", ["home"], {}),
  r1("støvsuge", "vacuum", "Jeg støvsuger stuen om fredagen.", "I vacuum the living room on Fridays.", ["home"], {}),
  r1("ordne", "sort out / fix", "Kan du ordne det inden fredag?", "Can you sort it out before Friday?", ["work", "home"], {}),
  irr("smøre", "spread / butter", "smører", "smurte", "smurt", "Jeg smører madpakker hver morgen.", "I make packed lunches every morning.", ["home"], { usage: "'smøre madpakke' is the daily Danish ritual of making lunch to take with you." }),
  irr("vaske op", "do the dishes", "vasker op", "vaskede op", "vasket op", "Jeg vasker op, du tørrer af.", "I'll wash up, you dry.", ["home"], {}),

  // --- getting about ------------------------------------------------------
  r1("stoppe", "stop", "Bussen stoppede ikke ved skolen.", "The bus didn't stop at the school.", ["movement"], {}),
  r1("parkere", "park", "Du må ikke parkere her.", "You can't park here.", ["movement", "admin"], {}),
  r1("dreje", "turn", "Drej til højre efter lyskrydset.", "Turn right after the traffic lights.", ["movement"], {}),
  r2("vende", "turn / return", "Vend bladet om.", "Turn the page over.", ["movement"], { usage: "'vende tilbage' = come back; 'vende om' = turn around." }),
  irr("forsvinde", "disappear", "forsvinder", "forsvandt", "forsvundet", "Min paraply er forsvundet.", "My umbrella has disappeared.", ["change"], { aux: "er" }),
  irr("dukke op", "turn up", "dukker op", "dukkede op", "dukket op", "Han dukkede op en time for sent.", "He turned up an hour late.", ["social", "movement"], { aux: "er" }),
  irr("afgå", "depart", "afgår", "afgik", "afgået", "Toget afgår fra spor 3.", "The train departs from platform 3.", ["movement", "admin"], { aux: "er", usage: "Timetable Danish. In speech people say 'køre'." }),
  irr("følge", "follow / accompany", "følger", "fulgte", "fulgt", "Følg skiltene til centrum.", "Follow the signs to the centre.", ["movement"], { usage: "'følge med' = keep up / come along." }),
  irr("bringe", "bring", "bringer", "bragte", "bragt", "Kan du bringe pakken med?", "Can you bring the parcel?", ["movement"], { usage: "Formal; everyday Danish says 'tage med' or 'have med'." }),
  irr("efterlade", "leave behind", "efterlader", "efterlod", "efterladt", "Han efterlod sin taske i toget.", "He left his bag on the train.", ["movement"], {}),
  irr("vende tilbage", "return", "vender tilbage", "vendte tilbage", "vendt tilbage", "Jeg vender tilbage med et svar.", "I'll get back to you with an answer.", ["movement", "communication"], { aux: "er", usage: "Also the standard closing line of a Danish work email." }),
  r1("vandre", "hike", "Vi vandrede langs kysten.", "We hiked along the coast.", ["movement", "body"], {}),
  r1("klatre", "climb", "Børnene klatrede i træet.", "The children climbed the tree.", ["body", "movement"], {}),
  r1("sejle", "sail", "Færgen sejler hver time.", "The ferry sails every hour.", ["movement"], {}),
  r1("lande", "land", "Flyet landede til tiden.", "The plane landed on time.", ["movement"], { aux: "er" }),

  // --- how things seem ----------------------------------------------------
  r1("ligne", "look like / resemble", "Hun ligner sin mor.", "She looks like her mother.", ["thinking"], { usage: "'ligne nogen' — no preposition." }),
  r1("virke", "seem / work", "Det virker ikke.", "It doesn't work.", ["thinking"], { usage: "Both 'appear' (han virker glad) and 'function' (maskinen virker ikke)." }),
  irr("se ud", "look / appear", "ser ud", "så ud", "set ud", "Du ser træt ud.", "You look tired.", ["thinking", "body"], { usage: "The 'ud' is what makes it 'look' rather than 'see'." }),
  irr("lyde", "sound", "lyder", "lød", "lydt", "Det lyder som en god idé.", "That sounds like a good idea.", ["thinking"], { usage: "'lyde som' = sound like." }),
  irr("forekomme", "seem / occur", "forekommer", "forekom", "forekommet", "Det forekommer mig underligt.", "It seems odd to me.", ["thinking"], {}),
  irr("føles", "feel (of a thing)", "føles", "føltes", "føltes", "Det føles forkert.", "It feels wrong.", ["feeling"], { usage: "The -s form is about how something feels; 'føle sig' is about how you feel." }),
  r1("opleve", "experience", "Jeg har oplevet meget i Danmark.", "I've experienced a lot in Denmark.", ["feeling"], {}),
  r1("opdage", "discover / notice", "Jeg opdagede fejlen for sent.", "I noticed the mistake too late.", ["thinking"], {}),
  r2("forsøge", "attempt", "Vi forsøgte at ringe flere gange.", "We tried to call several times.", ["thinking"], { usage: "More formal than 'prøve'." }),
  irr("lykkes", "succeed", "lykkes", "lykkedes", "lykkedes", "Det lykkedes mig at få tid hos lægen.", "I managed to get an appointment with the doctor.", ["change"], { usage: "Impersonal: 'det lykkedes mig at' = I managed to." }),
  irr("mislykkes", "fail", "mislykkes", "mislykkedes", "mislykkedes", "Forsøget mislykkedes.", "The attempt failed.", ["change"], {}),
  irr("bestå", "pass (an exam)", "består", "bestod", "bestået", "Jeg bestod modultesten i juni.", "I passed the module test in June.", ["school"], { usage: "'bestå af' = consist of — a completely different sense." }),
  r1("dumpe", "fail (an exam)", "Han dumpede første gang.", "He failed the first time.", ["school"], {}),
  r1("studere", "study", "Hun studerer til sygeplejerske.", "She's studying to be a nurse.", ["school"], {}),
  r1("vurdere", "assess", "Læreren vurderer din udtale.", "The teacher assesses your pronunciation.", ["school", "work"], {}),
  r2("måle", "measure", "Han målte rummet op.", "He measured the room.", ["work"], {}),
  r1("veje", "weigh", "Pakken vejer to kilo.", "The parcel weighs two kilos.", ["everyday"], {}),
  irr("tælle", "count", "tæller", "talte", "talt", "Tæl til ti, før du svarer.", "Count to ten before you answer.", ["thinking"], { usage: "Its past is identical to 'tale' in the past — context tells them apart." }),
  r1("beregne", "calculate", "Beregn prisen inklusive moms.", "Calculate the price including VAT.", ["money", "work"], {}),
  r1("levere", "deliver", "De leverer varerne på torsdag.", "They deliver the goods on Thursday.", ["work"], {}),
  r1("pendle", "commute", "Jeg pendler til København hver dag.", "I commute to Copenhagen every day.", ["work", "movement"], {}),

  // --- wanting, daring, having to -----------------------------------------
  irr("turde", "dare", "tør", "turde", "turdet", "Jeg tør ikke spørge ham.", "I don't dare ask him.", ["feeling"], { usage: "Modal-shaped: the next verb has no 'at'." }),
  irr("burde", "ought to", "bør", "burde", "burdet", "Du bør skrive til kommunen.", "You ought to write to the municipality.", ["core"], { usage: "Advice, softer than 'skal'." }),
  irr("gide", "be bothered", "gider", "gad", "gidet", "Jeg gider ikke lave mad i dag.", "I can't be bothered to cook today.", ["feeling"], { usage: "Very common in speech, and not rude — 'gider du lige' is how Danes ask a favour." }),
  r1("orke", "have the energy for", "Jeg orker ikke flere møder.", "I can't face any more meetings.", ["feeling"], {}),
  r1("behøve", "need", "Du behøver ikke at komme.", "You don't need to come.", ["core"], { usage: "Almost always in the negative." }),
  r1("nægte", "refuse / deny", "Han nægtede at underskrive.", "He refused to sign.", ["communication"], {}),
  r1("indrømme", "admit", "Jeg indrømmer, at jeg tog fejl.", "I admit I was wrong.", ["communication"], {}),
  r1("acceptere", "accept", "Vi accepterer kort og kontanter.", "We accept cards and cash.", ["admin"], {}),
  r1("respektere", "respect", "Man skal respektere reglerne.", "You have to respect the rules.", ["social"], {}),
  r2("overtale", "persuade", "Hun overtalte mig til at blive.", "She persuaded me to stay.", ["communication"], { usage: "'overtale nogen til at' + verb." }),
  r2("overbevise", "convince", "Han overbeviste os om, at det var rigtigt.", "He convinced us it was right.", ["communication"], { usage: "'overbevise nogen om' something." }),
  r1("forhandle", "negotiate", "De forhandlede om lønnen.", "They negotiated the salary.", ["work"], {}),
  r1("samarbejde", "cooperate", "Vi samarbejder med to andre skoler.", "We cooperate with two other schools.", ["work"], {}),
  r1("organisere", "organise", "Hun organiserede hele festen.", "She organised the whole party.", ["work", "social"], {}),
  r1("fejre", "celebrate", "Vi fejrer hendes fødselsdag på lørdag.", "We're celebrating her birthday on Saturday.", ["social"], {}),
  r1("irritere", "annoy", "Støjen irriterer mig.", "The noise annoys me.", ["feeling"], { usage: "'irritere sig over' = be annoyed about." }),
  r1("skuffe", "disappoint", "Resultatet skuffede os.", "The result disappointed us.", ["feeling"], {}),
  r1("overraske", "surprise", "Det overraskede mig, at hun sagde ja.", "It surprised me that she said yes.", ["feeling"], {}),
  irr("bekymre sig", "worry", "bekymrer sig", "bekymrede sig", "bekymret sig", "Han bekymrer sig for meget.", "He worries too much.", ["feeling"], { usage: "Reflexive, with 'om' or 'for'." }),
  r1("frygte", "fear", "Jeg frygter, at det bliver dyrt.", "I fear it will be expensive.", ["feeling"], {}),
  irr("fortryde", "regret", "fortryder", "fortrød", "fortrudt", "Jeg fortryder ikke, at jeg flyttede.", "I don't regret moving.", ["feeling"], {}),
  irr("sørge for", "make sure / see to", "sørger for", "sørgede for", "sørget for", "Sørg for at medbringe legitimation.", "Make sure to bring ID.", ["admin"], { usage: "The phrase every Danish letter from the authorities uses." }),
  irr("passe på", "be careful / look after", "passer på", "passede på", "passet på", "Pas på trinnet.", "Mind the step.", ["everyday", "social"], {}),

  // --- screens, paperwork and modern life ---------------------------------
  r1("downloade", "download", "Jeg downloadede appen i går.", "I downloaded the app yesterday.", ["admin", "everyday"], {}),
  r1("opdatere", "update", "Husk at opdatere din adresse i borger.dk.", "Remember to update your address on borger.dk.", ["admin"], {}),
  r1("installere", "install", "Han installerede programmet på min computer.", "He installed the program on my computer.", ["everyday"], {}),
  r1("klikke", "click", "Klik på det blå felt.", "Click on the blue field.", ["everyday"], {}),
  r1("printe", "print", "Kan du printe blanketten ud?", "Can you print the form out?", ["admin"], {}),
  r1("kopiere", "copy", "Jeg kopierede nøglen i går.", "I copied the key yesterday.", ["everyday"], {}),
  r1("slette", "delete", "Slet den gamle fil.", "Delete the old file.", ["everyday"], {}),
  r1("fungere", "function / work", "Systemet fungerer ikke i dag.", "The system isn't working today.", ["work"], {}),
  irr("logge ind", "log in", "logger ind", "loggede ind", "logget ind", "Log ind med dit NemID.", "Log in with your NemID.", ["admin"], {}),
  irr("optage", "record / take up", "optager", "optog", "optaget", "Mødet blev optaget.", "The meeting was recorded.", ["work"], { usage: "'optaget' also means busy or engaged — a taken seat, a busy line." }),
  irr("skrive under", "sign", "skriver under", "skrev under", "skrevet under", "Skriv under nederst på siden.", "Sign at the bottom of the page.", ["admin"], { usage: "The everyday form of 'underskrive'." }),
  r1("tegne", "draw", "Barnet tegnede et hus.", "The child drew a house.", ["school"], { usage: "'tegne en forsikring' = take out an insurance policy." }),
  r1("fotografere", "photograph", "Må jeg fotografere skiltet?", "May I photograph the sign?", ["everyday"], {}),
  r1("spille", "play (a game or instrument)", "Hun spiller klaver og fodbold.", "She plays piano and football.", ["social", "body"], { usage: "For games and instruments. Children at play is 'lege'." }),
  r1("lege", "play (as children do)", "Børnene leger i gården.", "The children are playing in the yard.", ["social"], {}),
  irr("synge", "sing", "synger", "sang", "sunget", "Vi sang med på sangen.", "We sang along with the song.", ["social"], {}),

  // --- society, environment and the news ----------------------------------
  irr("stemme", "vote / be right", "stemmer", "stemte", "stemt", "Jeg stemte ved kommunalvalget.", "I voted in the local election.", ["admin", "social"], { usage: "'det stemmer' = that's right; 'stemme på' = vote for." }),
  r1("demonstrere", "demonstrate / protest", "De demonstrerede foran rådhuset.", "They demonstrated in front of the town hall.", ["social"], {}),
  r1("protestere", "protest", "Beboerne protesterede mod byggeriet.", "The residents protested against the construction.", ["social"], { usage: "'protestere mod' something." }),
  r1("debattere", "debate", "Vi debatterede emnet i klassen.", "We debated the topic in class.", ["communication", "school"], {}),
  r1("påvirke", "affect / influence", "Vejret påvirker mit humør.", "The weather affects my mood.", ["change"], {}),
  r1("forandre", "change / transform", "Byen har forandret sig meget.", "The town has changed a lot.", ["change"], { usage: "'forandre sig' = change by itself." }),
  r1("forurene", "pollute", "Trafikken forurener luften i byen.", "Traffic pollutes the air in the city.", ["change"], {}),
  r2("genbruge", "recycle / reuse", "Vi genbruger glas og pap.", "We recycle glass and cardboard.", ["everyday"], {}),
  r1("sortere", "sort", "Man skal sortere sit affald.", "You have to sort your waste.", ["everyday", "admin"], {}),
  r1("beskytte", "protect", "Hjelmen beskytter dit hoved.", "The helmet protects your head.", ["body"], {}),
  r1("redde", "save / rescue", "Han reddede en hund fra vandet.", "He rescued a dog from the water.", ["social"], {}),
  r1("donere", "donate", "Hun donerede penge til foreningen.", "She donated money to the association.", ["social", "money"], {}),
  r2("anmelde", "report / review", "Du skal anmelde tyveriet til politiet.", "You have to report the theft to the police.", ["admin"], {}),
  r1("straffe", "punish", "Man kan blive straffet med en bøde.", "You can be punished with a fine.", ["admin"], {}),
  irr("forbyde", "forbid / ban", "forbyder", "forbød", "forbudt", "Det er forbudt at ryge her.", "Smoking is forbidden here.", ["admin"], { usage: "'det er forbudt at' is on signs everywhere." }),
  irr("tillade", "allow / permit", "tillader", "tillod", "tilladt", "Det er ikke tilladt at parkere her.", "Parking is not permitted here.", ["admin"], {}),
  irr("overholde", "comply with / keep to", "overholder", "overholdt", "overholdt", "Du skal overholde fristen.", "You have to keep to the deadline.", ["admin"], {}),
  irr("overtræde", "break (a rule)", "overtræder", "overtrådte", "overtrådt", "Han overtrådte reglerne.", "He broke the rules.", ["admin"], {}),
  r2("tilhøre", "belong to", "Cyklen tilhører min nabo.", "The bike belongs to my neighbour.", ["admin"], {}),
  r1("eje", "own", "De ejer huset selv.", "They own the house themselves.", ["money", "home"], {}),

  // --- health, family and the course of a life ----------------------------
  r1("behandle", "treat", "Lægen behandlede såret.", "The doctor treated the wound.", ["body"], { usage: "Also of treating a person a certain way: behandle nogen godt." }),
  r1("operere", "operate", "Hun blev opereret i knæet.", "She had an operation on her knee.", ["body"], {}),
  r1("vaccinere", "vaccinate", "Børnene bliver vaccineret i skolen.", "The children are vaccinated at school.", ["body", "admin"], {}),
  r1("hoste", "cough", "Han hostede hele natten.", "He coughed all night.", ["body"], {}),
  r2("nyse", "sneeze", "Jeg nyser, når jeg kommer ind i støv.", "I sneeze when I get into dust.", ["body"], {}),
  r2("bløde", "bleed", "Såret blødte lidt.", "The wound bled a little.", ["body"], {}),
  irr("komme sig", "recover", "kommer sig", "kom sig", "kommet sig", "Hun kom sig hurtigt efter operationen.", "She recovered quickly after the operation.", ["body"], { aux: "er" }),
  irr("gifte sig", "get married", "gifter sig", "giftede sig", "giftet sig", "De giftede sig sidste sommer.", "They got married last summer.", ["social"], { usage: "'gifte sig med' someone." }),
  irr("blive skilt", "get divorced", "bliver skilt", "blev skilt", "blevet skilt", "De blev skilt efter ti år.", "They got divorced after ten years.", ["social"], { aux: "er" }),
  r2("føde", "give birth", "Hun fødte en dreng i marts.", "She gave birth to a boy in March.", ["body"], { usage: "'blive født' = be born." }),
  irr("opdrage", "bring up / raise", "opdrager", "opdrog", "opdraget", "De opdrog deres børn tosproget.", "They raised their children bilingually.", ["social"], {}),
  r1("adoptere", "adopt", "De adopterede en hund fra internatet.", "They adopted a dog from the shelter.", ["social"], {}),
  irr("dø", "die", "dør", "døde", "død", "Min bedstemor døde sidste år.", "My grandmother died last year.", ["change"], { aux: "er", imperative: "dø" }),
  r1("leve", "live / be alive", "Han levede i Danmark i tredive år.", "He lived in Denmark for thirty years.", ["core"], { usage: "Being alive. Where you live is 'bo'." }),
  irr("ældes", "age", "ældes", "ældedes", "ældedes", "Vi ældes alle sammen.", "We all get older.", ["change"], { usage: "An -s verb with no active form — you cannot 'ælde' something." }),

  // --- the rest of the everyday ------------------------------------------
  r1("glæde", "please / delight", "Det glæder mig at høre.", "I'm glad to hear that.", ["feeling"], { usage: "'det glæder mig' is the polite way to say you're pleased." }),
  irr("blande sig", "interfere", "blander sig", "blandede sig", "blandet sig", "Bland dig ikke i deres skænderi.", "Don't interfere in their argument.", ["social"], { usage: "Reflexive, with 'i'." }),
  r1("undvære", "do without", "Jeg kan ikke undvære min cykel.", "I can't do without my bike.", ["everyday"], {}),
  r1("smadre", "smash", "Vinduet blev smadret i stormen.", "The window was smashed in the storm.", ["home"], {}),
  r2("fylde", "fill / turn (an age)", "Hun fylder tredive på fredag.", "She turns thirty on Friday.", ["everyday", "social"], { usage: "'fylde år' is how Danish says having a birthday." }),
  irr("tømme", "empty", "tømmer", "tømte", "tømt", "Tøm skraldespanden, tak.", "Empty the bin, please.", ["home"], {}),
  irr("vende om", "turn around", "vender om", "vendte om", "vendt om", "Vi vendte om ved broen.", "We turned back at the bridge.", ["movement"], {}),
  r1("hoppe", "hop / jump", "Barnet hoppede af glæde.", "The child jumped for joy.", ["body"], {}),
  r1("ryste", "shake", "Ryst flasken før brug.", "Shake the bottle before use.", ["body"], {}),
  r1("banke", "knock", "Bank på, før du går ind.", "Knock before you go in.", ["everyday"], {}),
  r1("hviske", "whisper", "Hun hviskede noget i mit øre.", "She whispered something in my ear.", ["communication"], {}),
  r2("råbe", "shout", "Råb ikke, jeg kan godt høre dig.", "Don't shout, I can hear you.", ["communication"], { usage: "'råbe ad nogen' = shout at someone." }),
  r1("trøste", "comfort", "Hun trøstede barnet.", "She comforted the child.", ["feeling", "social"], {}),
  r1("sukke", "sigh", "Han sukkede og lagde telefonen.", "He sighed and put the phone down.", ["feeling"], {}),
  r1("gabe", "yawn", "Jeg gabte hele mødet igennem.", "I yawned all through the meeting.", ["body"], {}),

  // --- the last of the five hundred: useful, and often forgotten ----------
  irr("hilse på", "say hello to", "hilser på", "hilste på", "hilst på", "Jeg hilste på naboen i opgangen.", "I said hello to the neighbour in the stairwell.", ["social"], { usage: "'hilse på nogen' — the 'på' is not optional." }),
  irr("kigge forbi", "drop by", "kigger forbi", "kiggede forbi", "kigget forbi", "Kig forbi, når du har tid.", "Drop by when you have time.", ["social"], {}),
  irr("ringe tilbage", "call back", "ringer tilbage", "ringede tilbage", "ringet tilbage", "Jeg ringer tilbage om en time.", "I'll call back in an hour.", ["communication"], {}),
  irr("lukke op", "open up / answer the door", "lukker op", "lukkede op", "lukket op", "Der er nogen, der banker — luk op.", "Someone's knocking — open the door.", ["home"], {}),
  irr("tage imod", "accept / receive", "tager imod", "tog imod", "taget imod", "Vi tager imod betaling med kort.", "We accept payment by card.", ["work", "money"], {}),
  irr("stille op", "stand for / help out", "stiller op", "stillede op", "stillet op", "Han stiller altid op, når vi mangler hjælp.", "He always steps up when we need help.", ["social"], {}),
  irr("slå op", "look up", "slår op", "slog op", "slået op", "Slå ordet op i ordbogen.", "Look the word up in the dictionary.", ["school"], {}),
  irr("finde frem", "get out / locate", "finder frem", "fandt frem", "fundet frem", "Find kvitteringen frem.", "Get the receipt out.", ["everyday"], {}),
  irr("holde op", "stop", "holder op", "holdt op", "holdt op", "Hold op med at tale i munden på hinanden.", "Stop talking over each other.", ["change"], {}),
  irr("holde fri", "take time off", "holder fri", "holdt fri", "holdt fri", "Jeg holder fri på fredag.", "I'm taking Friday off.", ["work"], {}),
  irr("tage fri", "take a day off", "tager fri", "tog fri", "taget fri", "Kan du tage fri i morgen?", "Can you take tomorrow off?", ["work"], {}),
  irr("sige op", "quit / hand in notice", "siger op", "sagde op", "sagt op", "Hun sagde sit job op i august.", "She quit her job in August.", ["work"], {}),
  irr("søge ind", "apply (for a place)", "søger ind", "søgte ind", "søgt ind", "Han søgte ind på universitetet.", "He applied to the university.", ["school"], {}),
  irr("melde afbud", "cancel your attendance", "melder afbud", "meldte afbud", "meldt afbud", "Jeg måtte melde afbud til festen.", "I had to cancel going to the party.", ["social", "admin"], {}),
  irr("give besked", "let someone know", "giver besked", "gav besked", "givet besked", "Giv besked, hvis du bliver forsinket.", "Let us know if you're delayed.", ["communication"], {}),
  irr("tage fejl", "be wrong", "tager fejl", "tog fejl", "taget fejl", "Jeg tog fejl af tidspunktet.", "I got the time wrong.", ["thinking"], {}),
  irr("have ret", "be right", "har ret", "havde ret", "haft ret", "Du har ret — det står i brevet.", "You're right — it says so in the letter.", ["thinking"], {}),
  irr("blive væk", "get lost / go missing", "bliver væk", "blev væk", "blevet væk", "Min handske er blevet væk.", "My glove has gone missing.", ["everyday"], { aux: "er" }),
  irr("gå i stå", "come to a standstill", "går i stå", "gik i stå", "gået i stå", "Trafikken gik i stå i myldretiden.", "The traffic came to a standstill in rush hour.", ["movement"], { aux: "er" }),
  irr("stå af", "get off", "står af", "stod af", "stået af", "Jeg står af ved næste stop.", "I'm getting off at the next stop.", ["movement"], { aux: "er" }),
  irr("ryge", "smoke / fly off", "ryger", "røg", "røget", "Det er forbudt at ryge indendørs.", "Smoking indoors is forbidden.", ["everyday"], { usage: "Also 'go flying': knappen røg af." }),
  irr("drømme", "dream", "drømmer", "drømte", "drømt", "Jeg drømte om min barndom.", "I dreamt about my childhood.", ["thinking"], { usage: "'drømme om' something." }),
  r1("mærke", "feel / notice", "Jeg mærkede en dråbe regn.", "I felt a drop of rain.", ["body"], { usage: "'mærke efter' = check how something feels." }),
  r2("røre", "touch / stir", "Rør ikke ved ovnen.", "Don't touch the oven.", ["body", "home"], { usage: "'røre ved' = touch; 'røre rundt' = stir." }),
  irr("ramme", "hit / affect", "rammer", "ramte", "ramt", "Bolden ramte vinduet.", "The ball hit the window.", ["body"], {}),
  r1("vinke", "wave", "Hun vinkede fra toget.", "She waved from the train.", ["social", "body"], {}),
  r1("pege", "point", "Han pegede på skiltet.", "He pointed at the sign.", ["body"], { usage: "'pege på' something." }),
  r1("nikke", "nod", "Hun nikkede og smilede.", "She nodded and smiled.", ["social", "body"], {}),
  r1("sparke", "kick", "Han sparkede bolden over målet.", "He kicked the ball over the goal.", ["body"], {}),
  r1("løfte", "lift", "Løft med benene, ikke med ryggen.", "Lift with your legs, not your back.", ["body", "work"], {}),
  irr("slippe", "let go / escape", "slipper", "slap", "sluppet", "Slip håndtaget nu.", "Let go of the handle now.", ["body"], { usage: "'slippe for' = get out of having to." }),
  irr("række", "hand / reach", "rækker", "rakte", "rakt", "Kan du række mig saltet?", "Can you pass me the salt?", ["social", "body"], { usage: "'række hånden op' = put your hand up." }),
  irr("lide", "suffer / like", "lider", "led", "lidt", "Jeg kan godt lide dansk mad.", "I like Danish food.", ["feeling"], { usage: "'kunne lide' is how Danish says 'like' — the 'kunne' is not optional." }),
  r1("tilføje", "add", "Tilføj din e-mail nederst.", "Add your email at the bottom.", ["admin", "communication"], {}),
  r1("erstatte", "replace", "Vi erstattede den gamle komfur.", "We replaced the old cooker.", ["home", "change"], {}),
  irr("afbryde", "interrupt / cut off", "afbryder", "afbrød", "afbrudt", "Undskyld, jeg afbryder lige.", "Sorry, I'm just interrupting.", ["communication"], {}),
  r1("forstyrre", "disturb", "Forstyrrer jeg?", "Am I disturbing you?", ["social"], {}),
  r2("udføre", "carry out", "Arbejdet blev udført på en dag.", "The work was carried out in a day.", ["work"], {}),
  r2("gennemføre", "complete / see through", "Hun gennemførte hele kurset.", "She completed the whole course.", ["school", "work"], {}),
  r1("opnå", "achieve", "Han opnåede et godt resultat.", "He achieved a good result.", ["change", "school"], {}),
  irr("opgive", "give up / state", "opgiver", "opgav", "opgivet", "Opgiv venligst dit telefonnummer.", "Please state your telephone number.", ["admin"], { usage: "Two senses: abandon, and state on a form." }),
  r2("anerkende", "acknowledge / recognise", "Uddannelsen er anerkendt i Danmark.", "The qualification is recognised in Denmark.", ["admin"], {}),
  irr("antage", "assume / take on", "antager", "antog", "antaget", "Jeg antager, at mødet er aflyst.", "I assume the meeting is cancelled.", ["thinking"], {}),
  r1("konkludere", "conclude", "Rapporten konkluderer, at prisen er for høj.", "The report concludes that the price is too high.", ["thinking"], {}),
  r2("uddybe", "elaborate", "Kan du uddybe det lidt?", "Can you elaborate on that a little?", ["communication"], { usage: "A very useful thing to say in the speaking test." }),
  r1("opsummere", "summarise", "Lad mig opsummere det vigtigste.", "Let me summarise the main points.", ["communication", "school"], {}),
  r1("fremhæve", "highlight / emphasise", "Hun fremhævede tre problemer.", "She highlighted three problems.", ["communication"], {}),
  r1("citere", "quote", "Han citerede fra artiklen.", "He quoted from the article.", ["communication", "school"], {}),
  r2("udtale", "pronounce", "Hvordan udtaler man 'rødgrød'?", "How do you pronounce 'rødgrød'?", ["school", "communication"], { usage: "'udtale sig om' = comment on." }),
  r1("bøje", "bend / inflect", "Bøj verbet i datid.", "Put the verb into the past tense.", ["school", "body"], { usage: "The grammar word for conjugating: 'at bøje et verbum'." }),
  r1("rime", "rhyme", "De to ord rimer ikke.", "The two words don't rhyme.", ["school"], {}),
  r1("tolke", "interpret", "Hun tolker for nye flygtninge.", "She interprets for new refugees.", ["work", "communication"], {}),
  r1("investere", "invest", "De investerede i en ny bil.", "They invested in a new car.", ["money"], {}),
  r1("fakturere", "invoice", "Vi fakturerer ved månedens udgang.", "We invoice at the end of the month.", ["money", "work"], {}),
  r1("refundere", "refund", "Beløbet bliver refunderet.", "The amount will be refunded.", ["money", "admin"], {}),
  r1("hæve", "withdraw / raise", "Jeg hævede penge i automaten.", "I withdrew money from the cash machine.", ["money"], { usage: "'hæve penge' at a machine, and 'hæve hånden' in class." }),
  irr("indsætte", "deposit / insert", "indsætter", "indsatte", "indsat", "Lønnen bliver indsat den sidste hverdag.", "The salary is paid in on the last working day.", ["money", "admin"], {}),
  r2("overføre", "transfer", "Jeg overfører pengene i dag.", "I'll transfer the money today.", ["money", "admin"], {}),
  r1("grine", "laugh", "Vi grinede af hans historie.", "We laughed at his story.", ["feeling", "social"], { usage: "'grine ad' something. The everyday word for laughing." }),
  r1("sulte", "starve / be hungry", "Jeg sulter — hvornår spiser vi?", "I'm starving — when are we eating?", ["body"], { usage: "'være sulten' is the ordinary way to say you're hungry." }),
  irr("slappe af", "relax", "slapper af", "slappede af", "slappet af", "Jeg slapper af foran fjernsynet.", "I relax in front of the TV.", ["feeling", "everyday"], {}),
  r1("hygge", "have a cosy time", "Vi hyggede med kaffe og kage.", "We had a cosy time with coffee and cake.", ["social", "feeling"], { usage: "The verb behind 'hygge'. 'hygge sig' is the usual form." }),
  r1("feste", "party", "De festede til klokken tre.", "They partied until three.", ["social"], {}),
  r1("booke", "book", "Jeg har booket et bord til fire.", "I've booked a table for four.", ["admin", "social"], { usage: "'bestille' is the more Danish word for the same thing." }),
  irr("afbestille", "cancel a booking", "afbestiller", "afbestilte", "afbestilt", "Jeg afbestilte værelset i sidste øjeblik.", "I cancelled the room at the last minute.", ["admin"], {}),
  r1("guide", "guide", "Hun guidede os gennem byen.", "She guided us through the town.", ["social"], {}),
  r1("blomstre", "bloom / flourish", "Træerne blomstrer i maj.", "The trees bloom in May.", ["change"], {}),
  r1("smelte", "melt", "Sneen smeltede på én dag.", "The snow melted in a day.", ["change"], {}),
  r1("dryppe", "drip", "Hanen drypper i køkkenet.", "The tap is dripping in the kitchen.", ["home"], {}),
  r1("lyne", "flash with lightning", "Det lynede og tordnede hele natten.", "There was thunder and lightning all night.", ["everyday"], {}),
  r1("tordne", "thunder", "Det tordner i det fjerne.", "It's thundering in the distance.", ["everyday"], {}),
  irr("brænde", "burn", "brænder", "brændte", "brændt", "Maden brændte på.", "The food burnt.", ["home"], { usage: "'brænde på' = burn (of food in a pan)." }),
  r1("varme", "heat / warm", "Jeg varmer suppen i mikroovnen.", "I'm heating the soup in the microwave.", ["home"], { usage: "'varme op' = heat up, and also warm up before sport." }),
  r1("køle", "cool", "Lad kagen køle af.", "Let the cake cool down.", ["home"], {}),
  r1("svede", "sweat", "Jeg svedte på cyklen hjem.", "I sweated on the ride home.", ["body"], {}),
  r1("ånde", "breathe", "Ånd roligt ind og ud.", "Breathe calmly in and out.", ["body"], { usage: "Everyday Danish says 'trække vejret'." }),
  r1("puste", "blow / puff", "Pust lysene ud.", "Blow the candles out.", ["body"], {}),
  r1("kravle", "crawl", "Barnet kravlede hen over gulvet.", "The baby crawled across the floor.", ["body", "movement"], {}),
  r1("rulle", "roll", "Bolden rullede ud på vejen.", "The ball rolled out into the road.", ["movement"], {}),
  r1("svinge", "swing / turn", "Sving til venstre ved kirken.", "Turn left at the church.", ["movement"], {}),
  r1("vippe", "tip / rock", "Stolen vipper — den er i stykker.", "The chair rocks — it's broken.", ["home"], {}),
];
