/**
 * Loads a snapshot produced by `export.ts` into the PostgreSQL database.
 *
 *     npx tsx prisma/data-migration/import.ts            # insert, fail on conflict
 *     npx tsx prisma/data-migration/import.ts --upsert   # re-runnable
 *
 * Idempotent with --upsert, so a partially completed run can simply be run
 * again. Ids are preserved exactly: cuids are portable, and keeping them means
 * every foreign key in the snapshot still resolves without a remapping table.
 */
import { PrismaClient } from "@prisma/client";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { TABLE_ORDER } from "./export";

const prisma = new PrismaClient();
const upsert = process.argv.includes("--upsert");

/**
 * Which fields identify a row, for --upsert. Tables with a plain `id` are
 * omitted and fall back to it; these are the ones with a composite or
 * non-`id` key.
 */
const IDENTITY: Record<string, (row: Record<string, unknown>) => object> = {
  itemConstruct: (r) => ({ itemId_constructId: { itemId: r.itemId, constructId: r.constructId } }),
  verificationToken: (r) => ({ identifier_token: { identifier: r.identifier, token: r.token } }),
};

/** ISO strings back into Dates, so Postgres gets timestamps not text. */
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function revive(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(row)) {
    out[k] = typeof v === "string" && ISO.test(v) ? new Date(v) : v;
  }
  return out;
}

async function main() {
  const path = resolve(process.cwd(), "prisma/data-migration/snapshot.json");
  const snapshot = JSON.parse(readFileSync(path, "utf8")) as Record<string, Record<string, unknown>[]>;

  let total = 0;

  // Parents before children — the order export.ts wrote them in. Inserting in
  // any other order would trip a foreign key.
  for (const table of TABLE_ORDER) {
    const rows = snapshot[table] ?? [];
    if (rows.length === 0) continue;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const delegate = (prisma as any)[table];
    if (!delegate) {
      console.warn(`  ! no delegate for "${table}" — skipping ${rows.length} rows`);
      continue;
    }

    for (const raw of rows) {
      const data = revive(raw);
      if (upsert) {
        const where = IDENTITY[table]?.(data) ?? { id: data.id };
        await delegate.upsert({ where, update: data, create: data });
      } else {
        await delegate.create({ data });
      }
    }

    total += rows.length;
    console.log(`  ${String(rows.length).padStart(5)}  ${table}`);
  }

  console.log(`\n${total} rows imported`);

  // Nothing in this schema uses a database sequence — every id is a cuid
  // generated by the application — so there are no sequences to reset after
  // inserting explicit ids. Worth stating, because forgetting that step is the
  // classic way a Postgres import breaks the next insert.
}

main()
  .catch((err) => {
    console.error("\nImport failed. Fix the cause and re-run with --upsert.\n", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
